- bin/activate
The PYTHONPATH exports seemed to be missing.
> activate exports

- .gitignore
- bin/haddock3.py
- examples/recipes/scoring/scoring.toml
- haddock/cns/engine.py
- haddock/cns/topology.py
- haddock/defaults.py
- haddock/modules/sampling/lightdock.py
- haddock/modules/scoring/default.py
- haddock/modules/topology/default.py
- haddock/ontology.py
- haddock/parallel.py
- haddock/pdbutil.py
- haddock/structure.py
- haddock/version.py
- haddock/workflow.py
This is a boring PR to make the code more accessible.
I do believe analogy is a great technique to match unrelated objects in order facilitate understanding and it is seen in many large projects out there in the wild. However me and @joaomcteixeira are getting lost in the ones that were present here since they were often actually quite metaphoric. 
Additionally, since we aim the project to have a wide reach, we need to also consider code accessibility and making it more boring can increase its readability. There will still be plenty of room for creative expression later on :)
With this PR I also linted to code to comply with [E501](https://www.flake8rules.com/rules/E501.html).
In this branch there are no tests yet, so I tested it by running the examples and checking if things were …
> Drop class name analogies favoring technical names

- haddock/defaults.py
After #21 I got this error when running `defaults.py`.
`data_path` was not being found within dictionary comprehension in `defaults.py`.
```bash
File "/home/joao/github/haddock3/haddock/defaults.py", line 42, in <dictcomp>
f"trans_vector_{i}": Path(data_path, 'toppar', 'initial_positions', f'trans_vector_{i}')
NameError: name 'data_path' is not defined
```
reverting to a for-loop solves the issue. But I am really puzzled by this issue. I don't understand why `data_path` was not being found inside the dictionary comprehension. Any ideas?
> data_path not being found

- examples/recipes/double_scoring/scoring.toml
- examples/recipes/full_scoring/scoring.toml
- examples/recipes/sampling/lightdock.toml
Some names `flavour` remained after #21. This broke any runs where flavour was not the `default`, for example in `lightdock`.
> renames flavour to mode missing files

- README.md
- src/haddock/defaults.py
This updates the install instructions and change the code to look for `bin/cns` instead of `bin/cns/cns`
> Correct `ln` command typo and updates `CNS_EXE` path to `bin/cns`

- examples/docking/docking.toml
- examples/scoring/scoring.toml
- examples/thirdparty/lightdock/lightdock.toml
- src/haddock/clis/cli.py
- src/haddock/gear/parameters.py
- src/haddock/gear/prepare_run.py
- src/haddock/libs/libutil.py
- src/haddock/modules/__init__.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/sampling/lightdock/__init__.py
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
- src/haddock/structure.py
- src/haddock/workflow.py
Continue implementations discussed in #53.
Here's the draft PR while I work on it. Comments and suggestions are very welcomed.
Cheers,
> Removing `stage` key as a requirement for the configuration file

- src/haddock/clis/cli.py
(re)Closes #11 and honours #12
We have schedule additional setup steps but those will be implemented in future PRs, here only the engine flow is defined.
> adds setup only option

- setup.py
- src/haddock/clis/cli.py
- src/haddock/libs/libutil.py
- tests/test_cli.py
- tests/test_libutil.py
* modularizes `cli.py` by decoupling the `main` from the `argparse` and by adding additional intermediate functions to allow control flow at any point in future. I link to program on demand but these functions are minimal and provide a great deal of modularity.
* abstracts some other functions related to CLI arguments
* adds tests
This PR gently assumes #84 will be accepted :warning: do not merge here if #84 is rejected. :warning:
> Modularizes cli.py

- src/haddock/libs/libsubprocess.py
- src/haddock/modules/analysis/clustfcc/__init__.py
`clustfcc.__init__.py` missed update after #66. Also, `Job` brokes using `Path` in `Job`. This small PR solves both issues.
> Updates `clusterfcc` to #66 - missing

- src/haddock/clis/cli.py
- src/haddock/gear/prepare_run.py
- src/haddock/gear/restart_run.py
- src/haddock/libs/libutil.py
- src/haddock/modules/__init__.py
- tests/test_cli.py
- tests/test_gear_restart.py
The `--restart` option was not working. Now it works.
* if `--restart` is given, the previous run folder is **not** deleted in case it existed.
* the "previous" module folder is obtained by the order parameter and not considering the last created folder in the series `00_`.
Closes #75
> Reactivates `--restart` option

- src/haddock/libs/libutil.py
Thanks, @amjjbonvin for spotting this out. Developing software for GRID/Cloud and 1-CPU cases. This is what I meant by >100% coverage the last time.
I will add tests to the whole codebase after the major PRs are merged.
> Corrects for the rare case of number of CPUs = 0

- src/haddock/gear/config_reader.py
- src/haddock/modules/analysis/clustfcc/__init__.py
Removes a remaining `toml` dependency left unnoticed after #81
> Removes remaining toml dependency after #81

- .github/workflows/py38.yml
- .github/workflows/py39.yml
Since this repository is [already activated in codecov](https://app.codecov.io/gh/haddocking/haddock3/commits?page=1), we can add the codecov report from the github actions. I forgot to check this on #110 .
> Codecoving

- src/haddock/modules/analysis/caprieval/defaults.cfg
Make the reference parameter more clear to `""` instead of `false`
> Update `caprieval` defaults.cfg

- src/haddock/gear/prepare_run.py
- src/haddock/libs/libsubprocess.py
- src/haddock/libs/libworkflow.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
Adds global variables for CNS runs according to what we discussed.
@amjjbonvin can you read over the documentation of `CNSJob` and see if they agree with expectations? Also, can you test out the examples? With this changes the `rigid-body` example broke. Likely because the `RUN` variable does not point to the same place as before. Should we update the var or the CNS scripts?
**EDIT:** likely the example broke because of #132
> Adds support for global variables for CNS

- src/haddock/modules/analysis/caprieval/__init__.py
This PR fixes #154 
```tsv
model	fnat	irmsd	lrmsd	ilrmsd	
rigidbody_1.pdb	0.167	3.96	12.74	5.51	
rigidbody_2.pdb	0.083	4.78	68.65	5.90	
rigidbody_3.pdb	0.500	1.28	2.65	1.62	
rigidbody_4.pdb	0.500	1.30	64.36	1.58	
rigidbody_5.pdb	0.556	1.46	3.60	2.20	
```
```tsv
model	fnat	irmsd	lrmsd	ilrmsd	
rigidbody_1.pdb	0.167	3.96	12.74	5.51	
rigidbody_2.pdb	0.083	4.78	14.49	5.90	
rigidbody_3.pdb	0.500	1.28	2.65	1.62	
rigidbody_4.pdb	0.500	1.30	2.49	1.58	
rigidbody_5.pdb	0.556	1.46	3.60	2.20	
```
> Fixes arrays being overwritten in `caprieval`

- src/haddock/libs/libontology.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
This PR implements ensemble support for docking and closes #148.
Note that for this to work I had to change the data structure of `topoaa`, meaning that all modules that come after it need to be refactored, meaning meaning that we can no longer do refinement runs (but I'm not sure if this was possible anyway `topoaa > flexref`), let's work on this example in another PR.
> Implement ensemble support for docking in CNS-based modules

- src/haddock/libs/libcns.py
- src/haddock/libs/libfunc.py
- tests/test_libcns.py
* improves filtering function from #163 where *empty vars*  where filtered out (not written to CNS)
* applies the filter to variables in `topoaa/input/vars`, that is nested vars two levels deep.
* `eval` string now a template
* adds some tests
* combo: variables that are strings can be nullified with `''` but also with `None`. But we don't need to tell that to anyone. Just use `''`.
> improves on #163

- src/haddock/libs/libcns.py
- tests/test_libcns.py
Empty strings `""` are now written to CNS file. I had misunderstood the requirements from #162.
> empty strings are written to CNS

- src/haddock/libs/libcns.py
- src/haddock/libs/libpdb.py
- src/haddock/libs/libutil.py
- src/haddock/modules/topology/topoaa/__init__.py
- tests/test_libutil.py
* `input` params from `topoaa` are now distributed over molecules.
* `input` params are written to the CNS file, both defaults and the user injected, without the `mol` suffix.
* In the case of docking two molecules (`A` and `B`), where `B` is an ensemble, each model of the ensemble will get the **same** parameters corresponding to the molecule number: `A` gets `mol1` and all models of `B` get `mol2`.
* For the particular case of `input`, new parameters can be added even if they are not defined in the `defaults.cfg`. This allows for more flexibility, though it adds responsibility to the user as typos won't be spotted.
* Adds correct sorting for integer suffixed files: for example, `file_1`, `file_2`, `file_10`, are now sorted properly according to their numeration (useful for ensembles). …
> `input` params in `topoaa/defaults.cfg` now with proper behaviour

- requirements.txt
- requirements.yml
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/defaults.cfg
I re-implemented the output function [because life is better with pandas](https://images-na.ssl-images-amazon.com/images/I/61a0D1YzjNL.jpg) 🐼 
***
This closes #153.
> Add option to "sortby" in `caprieval`

- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/defaults.cfg
This is a remake of #182, now [in pure-python implementation since we should not use `pandas`](https://github.com/haddocking/haddock3/pull/182#issuecomment-987864556) which again closes #153.
> Add option to sort-by in `caprieval`

- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
Small tweak to the logs, think we missed some in #159
> Tweak logs

- examples/docking-protein-protein/docking-protein-protein-hpc.cfg
- src/haddock/clis/cli_bm.py
- src/haddock/libs/libhpc.py
- src/haddock/libs/libworkflow.py
- src/haddock/modules/__init__.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
I implemented a new `libhpc` to handle the HPC executions (SLURM, but we can add TORQUE later). I tried my best to follow the same design of Brian's `libparallel`.
I also implemented `queue_limit` that defines the size of the submission batches and `concat`, similar to what we have in haddock2.4
```python
concat = 1
queue_limit = 100
```
```
[2021-12-09 12:44:57,404 __init__ INFO] [topoaa] Running CNS Jobs n=11
[2021-12-09 12:44:57,404 libhpc INFO] Concatenating, each .job will produce 5 (or less) models
[2021-12-09 12:44:57,405 libhpc INFO] > Running batch 1/1
[2021-12-09 12:44:57,503 libhpc INFO] >> topoaa_1.job submitted
[2021-12-09 12:44:57,531 libhpc INFO] >> topoaa_2.job submitted
[2021-12-09 12:44:57,555 libhpc INFO] >> topoaa_3.job submitted
[2021-12-09 12:44:57,556 libhpc INFO] …
```
> Implement HPC execution

- src/haddock/libs/libparallel.py
This closes #196 
```
[2021-12-13 15:50:17,612 __init__ INFO] [rigidbody] Running CNS Jobs n=20
[2021-12-13 15:51:53,516 libparallel INFO] >> 01_rigidbody/rigidbody_1.inp completed 5% 
[2021-12-13 15:51:59,156 libparallel INFO] >> 01_rigidbody/rigidbody_2.inp completed 10% 
[2021-12-13 15:52:00,784 libparallel INFO] >> 01_rigidbody/rigidbody_3.inp completed 15% 
[2021-12-13 15:52:02,497 libparallel INFO] >> 01_rigidbody/rigidbody_4.inp completed 20% 
[2021-12-13 15:52:05,320 libparallel INFO] >> 01_rigidbody/rigidbody_5.inp completed 25% 
[2021-12-13 15:52:05,320 libparallel INFO] >> 01_rigidbody/rigidbody_6.inp completed 30% 
[2021-12-13 15:52:05,320 libparallel INFO] >> 01_rigidbody/rigidbody_7.inp completed 35% 
[2021-12-13 15:52:05,320 libparallel INFO] >> 01_rigidbody/rigidbody_8.inp …
```
> Sort tasks while initializing `libparallel`

- src/haddock/clis/cli_bm.py
- src/haddock/clis/cli_dmn.py
Made some very minor changes to the benchmark scripts, mostly changing the name of some variables and removing one of the `create_cfg_scn_2` which did not make much sense. 
But doing so I just noticed that the benchmark scenarios are hardcoded in the script, this is not very practical and we should have a more flexible way of defining it, let's work on it on https://github.com/haddocking/haddock3/issues/194
> Small tweaks to the benchmark scripts

- src/haddock/modules/sampling/rigidbody/cns/rigidbody.cns
Replaced wrong environment variable. 
***
Closes  #206
> Use `MODDIR` instead of `MODRUN` `rigidbody.cns`

- examples/docking-protein-protein/docking-protein-protein-hpc.cfg
- src/haddock/libs/libhpc.py
- src/haddock/libs/libworkflow.py
- src/haddock/modules/__init__.py
> Add `queue` parameter to `libhpc`

- src/haddock/libs/libparallel.py
- src/haddock/libs/libsubprocess.py
- src/haddock/libs/libworkflow.py
- src/haddock/modules/__init__.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
To facilitate running the `.inp` CNS scripts independently from the HADDOCK3 shell we need a file with the environment variables that can be sourced independently. FYI, when the HADDOCK3's python shell runs the environment variables are sent directly to the `subprocess.Popen`.
Saving the `envvars` to a file is now part of the `BaseHaddockModule` class and saving triggers automatically for all Modules that use CNS. The new file is called `envvars` and is inside each modules folder `00_`, `01_`, etc; as long as that module uses CNS.
The `envvars` file has a `COMMON_PATH_HD3` variable that can be changed easily in case we transport the haddock installation and the examples folder to another computer.
`source envvars` and you are good to go.
Example:
```bash
#!/bin/bash
export …
```
> Export environment variables to a file per module.

- tox.ini
To ensure we don't forget `print` statements around the code before emerging.
> Starts using `flake8-print`

- examples/docking-protein-DNA/docking-protein-DNA.cfg
- examples/docking-protein-ligand/docking-protein-ligand.cfg
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/defaults.cfg
This PR closes #158 by allowing the calculation of the CAPRI metrics for DNA/Ligands. 
It also partially solves #179 by adding the logic to check if the given reference structure has the exact numbering/composition/chain as the target model, else it falls back and uses the best scored structure from the previous stage as reference.
> Add support for DNA/Ligands in `caprieval`

- src/haddock/libs/libhpc.py
> Edit `libhpc` with new variable scheme

- src/haddock/modules/analysis/caprieval/capri.py
Small typos, big consequences. 🤦🏽 
This PR fixes #236 
```
model                 rank     score     irmsd      fnat     lrmsd    ilrmsd
04_flexref/flexref_1.pdb           1   -66.080     0.548     0.962     1.263     1.250
04_flexref/flexref_3.pdb           2   -53.998     0.572     0.962     1.330     1.319
04_flexref/flexref_2.pdb           3   -52.696     0.866     0.923     1.683     1.662
04_flexref/flexref_5.pdb           4   -49.181     0.812     0.923     2.294     2.271
04_flexref/flexref_4.pdb           5   -12.472     1.849     0.769     5.824     5.775
```
> fix `caprieval` reading from the wrong reslist when assembling the numbering reference

- src/haddock/gear/prepare_run.py
Reimplements a function that was silently disabled by #219.
Validates module's names after reading the configuration file.
> Validates module's name

- src/haddock/libs/libontology.py
- src/haddock/modules/analysis/clustfcc/__init__.py
This PR closes #243 by adding the following to `libontology`
```python
self.clt_id = None
self.clt_rank = None
self.clt_model_rank = None
```
* * *
And since @amjjbonvin commented that:
> It would also be handy to have the output saved on file.
I used the information to write a detailed version of `cluster.out` named `clustfcc.txt` (both are written)
```
Cluster 1 -> 17 3 8 9 11 12 14 16 18 24 26 29 35 37 38 48 62 73 77 78 79 83 84 
Cluster 2 -> 74 10 31 82 86 93 98 
Cluster 3 -> 85 5 7 40 81 95 
Cluster 4 -> 80 6 28 33 50 
Cluster 5 -> 61 41 45 49 71 
Cluster 6 -> 44 15 32 39 43 
Cluster 7 -> 2 53 55 57 58 
Cluster 8 -> 59 64 66 67 
```
```
Clustering parameters 
> contact_distance_cutoff=5.0A
> fraction_cutoff=0.6
> threshold=4
> strictness=0.75 …
```
> Add cluster information in `PDBobject`

- examples/docking-protein-protein/docking-protein-protein.cfg
- src/haddock/modules/analysis/clustfcc/__init__.py
This PR closes #253 by adding a logic to **decrease** the threshold in case no clusters were found. This changed threshold is then passed back to the parameter dictionary so it can be written in the detailed `clustfcc.txt`.
> Implement automatic threshold in `clustfcc`

- src/haddock/modules/topology/topoaa/__init__.py
- src/haddock/modules/topology/topoaa/defaults.cfg
Useful when the next module is `emscoring`.
Activate it with the new parameter
```toml
[topoaa]
limit = false
```
@amjjbonvin
> No limit of 20 molecules for `topoaa`

- src/haddock/libs/libontology.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/emref/defaults.cfg
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/flexref/defaults.cfg
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/refinement/mdref/defaults.cfg
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/sampling/rigidbody/defaults.cfg
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/scoring/emscoring/defaults.cfg
- src/haddock/modules/topology/topoaa/__init__.py
- src/haddock/modules/topology/topoaa/defaults.cfg
This PR closes #227 by adding a fault tolerance logic to the modules.
The new parameter `tolerance` is set in `defaults.cfg` as % and the check is made directly into `ModuleIO`.
> Implement fault tolerance

- src/haddock/libs/libontology.py
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/clustfcc/__init__.py
This PR closes #251 by implementing the `lt`, `gt` and `eq` to `PDBFile`.
> Implement `lt`, `gt` and `eq` operators to `PDBFile`

- src/haddock/libs/libsubprocess.py
- src/haddock/modules/analysis/clustfcc/__init__.py
Closes #245 
Creates a proper subclass. I decided to use `make_cmd` instead of using the `super()` function because `make_cmd` can serve a prestep for testing or any other functionality.
> Implemented `JobInputFirst`

- src/haddock/__init__.py
- src/haddock/gear/parameters.py
- src/haddock/gear/prepare_run.py
- src/haddock/libs/libhpc.py
- src/haddock/libs/libutil.py
- src/haddock/libs/libworkflow.py
- src/haddock/modules/__init__.py
- src/haddock/modules/base_cns_module.py
- src/haddock/modules/defaults.cfg
- tests/test_libutil.py
After the last months PRs, I noticed the way module's global parameters were defined was not escalating properly.
Now parameters are properly separated into:
1. global parameters that serve diverse purposes but are **not** injectable into modules
2. global parameters that are applicable to modules but that can be defined also per module basis; in these cases module-defined parameters always overwrite global-defined ones
3. module-specific parameters that are defined in the default config files
Also, the most critical point of refactor concerns point 2. Before, parameters referent to 2. where being defined in several different places. Now, I implemented engines to retrieve the those parameter's defaults wherever they are needed, yet the parameter values are defined in a single place …
> Refactored the parameter flow

- examples/docking-protein-protein/docking-protein-protein-cltsel.cfg
- src/haddock/modules/analysis/seletopclusts/__init__.py
- src/haddock/modules/analysis/seletopclusts/defaults.cfg
This pr closes #282  by implementing a different logic to loop over the target cluster rankings
> Add option to select all clusters in `seletopclusts`

- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/capri.py
This pr closes #284 by adding the DockQ metric to `caprieval`, based on their own code , the dockq metric is given by:
```python
DockQ=(float(fnat) + 1/(1+(irms/1.5)*(irms/1.5)) + 1/(1+(Lrms/8.5)*(Lrms/8.5)))/3
```
https://github.com/bjornwallner/DockQ/blob/3735c160050f1e9128d2ccb23a0a1945aa98b5b2/DockQ.py#L361
> Add dockq metric to `caprieval`

- examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
- examples/docking-protein-homotrimer/docking-protein-homotrimer-test.cfg
- examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
- examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
- examples/docking-protein-peptide/docking-protein-peptide-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-mdref-test.cfg
- examples/docking-protein-peptide/docking-protein-peptide-test.cfg
- examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
- examples/docking-protein-protein/docking-protein-protein-full.cfg
- examples/docking-protein-protein/docking-protein-protein-hpc-test.cfg
- examples/docking-protein-protein/docking-protein-protein-mdref-full.cfg
- examples/docking-protein-protein/docking-protein-protein-mdref-test.cfg
- examples/docking-protein-protein/docking-protein-protein-test.cfg
- examples/refine-complex/refine-complex-test.cfg
- src/haddock/modules/topology/topoaa/__init__.py
- src/haddock/modules/topology/topoaa/defaults.cfg
@amjjbonvin one of the things we discussed in today's IVRESSE meeting was the possibility to remove the `input` layer from the `topoaa` module such that we have only `mol1`, `mol2`, etc, directly in the top layer of the config file. As you can see from the changes in this PR, removing the `input` layer adds no burden to the Python API (see changes in the `topoaa/__init__.py` file. I have these changes already prepared for the #274 if you accept them.
@sverhoeven
> Remove `input` layer in `topoaa` module.

- examples/run_examples-full.py
- examples/run_tests.py
As pointed in https://github.com/haddocking/haddock3/pull/297#discussion_r794655989, these whitespaces must be kept but this information is not present in the document, this PR adds a minor comment about this so they are not removed by mistake.
> Add documentation about whitespaces in `run_test.py`

- examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
- examples/docking-protein-DNA/docking-protein-DNA-test.cfg
- examples/docking-protein-homotrimer/docking-protein-homotrimer-test.cfg
- examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
- examples/docking-protein-ligand/docking-protein-ligand-test.cfg
- examples/docking-protein-peptide/docking-protein-peptide-mdref-test.cfg
- examples/docking-protein-peptide/docking-protein-peptide-test.cfg
- examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
- examples/docking-protein-protein/docking-protein-protein-hpc-test.cfg
- examples/docking-protein-protein/docking-protein-protein-mdref-test.cfg
- examples/docking-protein-protein/docking-protein-protein-test.cfg
- examples/refine-complex/refine-complex-test.cfg
- examples/scoring/scoring-test.cfg
This PR is a redo of #297, this time adding `tolerance = 20` to all the examples that contain `-test.cfg` and keeping the trailing white spaces
> [REDO] Set tolerance of modules in the workflow integration tests to 20% 

- src/haddock/libs/libhpc.py
The default values for the `libhpc.HPCScheduler` was swapped. This was not affecting the runs because `modules.get_engine` was passing the correct values. This PR corrects the defaults assignments.
> Correct `libhpc.HPCScheduler` defaults

- src/haddock/__init__.py
- src/haddock/modules/analysis/caprieval/defaults.yaml
- src/haddock/modules/analysis/clustfcc/defaults.yaml
- src/haddock/modules/analysis/seletop/defaults.yaml
- src/haddock/modules/analysis/seletopclusts/defaults.yaml
- src/haddock/modules/defaults.yaml
- src/haddock/modules/refinement/emref/defaults.yaml
- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/refinement/mdref/defaults.yaml
- src/haddock/modules/sampling/gdock/defaults.yaml
- src/haddock/modules/sampling/lightdock/defaults.yaml
- src/haddock/modules/sampling/rigidbody/defaults.yaml
- src/haddock/modules/scoring/emscoring/defaults.yaml
- src/haddock/modules/topology/topoaa/defaults.yaml
Correct `explevels` definitions in `defaults.yaml` to: `easy`, `expert`and `guru`.
Closes #305 
@sverhoeven please update your scripts accordingly.
> Correct `explevels`

- requirements.txt
- requirements.yml
Updates `requirements` to the latest version of `pdb-tools` to ensure the latest is used. Comes after: https://github.com/haddocking/pdb-tools/pull/117 and https://github.com/haddocking/pdb-tools/pull/119
These are needed for #143 and #144
> update `pdbtools` dependencies

- requirements.txt
- requirements.yml
Update dependency versions, forcing exact numbers. This is important because for now, HADDOCK3 is *under development* but also in the future HADDOCK3 is mostly to be used as a program instead of a library, so enforcing exact dependency numbers avoids possible discrepancies between installations.
Because we have little dependencies, we can, once in a while, review the dependencies updates manually. I am looking for stability instead of cutting-edge.
> Update deps versions - forcing exact numbers

- src/haddock/modules/__init__.py
- tests/test_modules_general.py
Module's categories have now a hierarchy defined in `modules/__init__.py.category_hierarchy`. With tests.
@sverhoeven
> Add hierarchy to the categories

- src/haddock/clis/cli_cfg.py
- src/haddock/gear/yaml2cfg.py
- src/haddock/modules/topology/topoaa/defaults.yaml
- tests/configs/yml_example.yml
- tests/test_cli_cfg.py
- tests/test_yaml2cfg.py
* Corrects the `haddock-cfg` client
* Adds tests
* corrects a missing `intermediate` that ware remaining in the  `topoaa`
> Corrects explevels in `haddock3-cfg` choices

- src/haddock/gear/yaml2cfg.py
- tests/test_yaml2cfg.py
In #322 I removed `hidden` from `CNS` input and still considered for `haddock-cfg`. What a lapse. This corrects it properly. Related to #321
> Corrects #322

- .github/pull_request_template.md
- CONTRIBUTING.md
Completes the `CONTRIBUTING` guidelines. This should be enough. The `CONTRIBUTING` file is not an explanation of how to use github or how to dev code, but how to interact with the project. Do you find something missing? You can read the rendered markdown version of the file [here](https://github.com/haddocking/haddock3/blob/contri/CONTRIBUTING.md).
> Further improves CONTRIBUTING

- examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/capri.py
- src/haddock/modules/analysis/caprieval/defaults.yaml
- tests/test_module_caprieval.py
You are about to submit a new Pull Request. Before continuing make sure
you read the [contributing guidelines](CONTRIBUTING.md) and you comply
with the following criteria:
as explained in contributing guidelines. You wrote explanatory comments for
those tricky parts.
`python run_tests.py -b`
other programming languages to HADDOCK3
small functions instead. But, you can use classes if there's a purpose.
by the HADDOCK team
* * *
Closes #352 by implementing a cluster-based output to `caprieval`;
it now has two output files: `capri_ss.tsv` for single-structure and `capri_clt.tsv` for cluster-based, if there is no cluster information in the models, then only `capri_ss.tsv` is generated. 
The models inside each cluster are ranked by score; so by setting `clt_threshold=4` (new parameter) the …
> Impelement cluster-based output in `caprieval`

- src/haddock/libs/libhpc.py
> Fix % display in `libhpc`

- src/haddock/modules/topology/topoaa/defaults.yaml
---
Fix small typo that tripped up my defaults parser.
> tile in topoaa.defaults.mol1 should be title

- src/haddock/modules/topology/topoaa/defaults.yaml
- tests/test_modules_general.py
---
Updates `defaults.yaml` tests after #361. Thanks to @sverhoeven
> Improves `defaults.yaml` tests

- requirements.txt
---
The `pip install -r requirements.txt` gives following error
```
Running command git clone -q git://github.com/joaorodrigues/fcc /tmp/pip-req-build-vzyf32sz
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
This PR updates the location from where fcc is installed.
> Install fcc over https

- src/haddock/libs/libio.py
- src/haddock/libs/libsubprocess.py
- tests/__init__.py
- tests/test_libio.py
---
If the `YAML` was an empty file (rare, but possible) the `read_yaml` function was returning a `None`, which creates inconsistent types for implemented parameter reading/setup pipelines. Now, the function returns an empty dictionary, instead.
Found this when testing some ideas discussed with @mgiulini this morning.
> Read yaml should return always a dictionary

- src/haddock/__init__.py
- src/haddock/core/defaults.py
- tests/test_core.py
the maximum number of molecules allowed is now defined in a single place: the `mandatory.yaml` configuration file.
> Max number of molecules defined in a single place - the config

- src/haddock/libs/libutil.py
- src/haddock/libs/libworkflow.py
- tests/test_libutil.py
---
Corrects edge cases in #378 when having 10 modules because module count starts at `0`.
> Corrects edge case in zero filling modules folder names

- src/haddock/gear/expandable_parameters.py
- src/haddock/gear/prepare_run.py
- tests/test_gear_expandable_parameters.py
---
While developing for #382, I found this part of the code poorly documented. Here, I add docs, tests, and correct a minor implementation.
> Improve docs and tests for a part of the `setup_run` function

- src/haddock/core/defaults.py
- src/haddock/gear/restart_run.py
- src/haddock/modules/__init__.py
---
#378 broke `--restart` option for some cases.
Corrects and updates definitions for module's folders numeric prefix.
> modules prefix to defaults

- src/haddock/modules/analysis/caprieval/capri.py
---
This PR adds `WAT` to the list of residues to be ignored when calculating the capri metrics and closes #398, this allows `caprieval` to be executed after any module that adds water molecules to the models.
> Ignore `WAT` residues in `caprieval`

- examples/scoring/mdscoring-test.cfg
- src/haddock/modules/scoring/mdscoring/cns/mdscoring.cns
---
Modified the `mdscoring` script to avoid writing the solvent unless `keepwater` is set to true in the config file.
***
This PR fixes #400
> Remove solvent molecules from the output of `mdscoring`

- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
Before the alignment was just taking sections that overlap, now it should correctly use the numbering reference, also improved a bit the readability of the sequence alignment function and updated the tests.
> Bugfix for numbering reference between model and receptor

- src/haddock/modules/base_cns_module.py
- tests/test_libutil.py
---
This bug did **not** cause any problems in the past. But was causing problems with #409. Decided to solve it in a separate PR for simplicity.
> Correct small (future) bug in reading `self_contained` parameter

- src/haddock/modules/analysis/clustfcc/__init__.py
---
corrected denominator in `clustfcc` #411
> amend threshold behavior in clustfcc

- examples/compare_runs.py
- examples/run_tests.py
- src/haddock/clis/cli_cfg.py
- tox.ini
Updates CI to the new [flake8-print](https://pypi.org/project/flake8-print/) v5, which changed the error codes. See its changelog.
> updates CI to flake8-print v5

- src/haddock/gear/config_writer.py
- tests/test_gear_config_writer.py
- tests/test_modules_general.py
---
* related to #407, #409
* Add more unit tests to `config_writer` to further confirm https://github.com/haddocking/haddock3/pull/409#issuecomment-1114568693 (everything was working)
* Improves new lines spacing parameters and headers in config writing. 
@sverhoeven
> Additional unit tests and newline improvements in `config_writer`

- CONTRIBUTING.md
- tox.ini
As the number of unit tests increases, the current `pytest` command in `tox` is becoming very verbose. This PR reduces the verbosity of `tox -e py39` command. If you want fully verbosity, run `tox -e py39 -- -vv`. Also updated the docs.
> Reduce `pytest` verbosity

- src/haddock/core/defaults.py
- src/haddock/gear/restart_run.py
- src/haddock/modules/__init__.py
- tests/test_modules_general.py
---
While preparing #425, I realized the way we search for step folders (`0_topoaa`, `1_rigidbody`, etc...) in a run directory can be improved because before we were considering only folders starting with a number. Now, we consider folders starting with a number, plus `_`, and that are named the same as modules.
> Improves method to find step folders in a run directory

- examples/run_tests.py
- src/haddock/gear/restart_run.py
- src/haddock/libs/libutil.py
---
* Corrects a bug in `--restart` introduced after #427
* Add `--restart` test to `run_tests.py`
If I would tell @douweschulte the amount of tests we would need to avoid these bugs that would be captured at compile time in Rust... :stuck_out_tongue_closed_eyes: Joking. Python dynamic typing is great :-D
> Corrects bug in `--restart`

- docs/reference/gear/config_reader.rst
- docs/reference/gear/config_writer.rst
- docs/tutorials/index.rst
- docs/tutorials/user_config.rst
- src/haddock/gear/config_reader.py
- src/haddock/gear/config_writer.py
- src/haddock/modules/__init__.py
---
* Adds user documentation on how to use, read, and write configuration files
* Improves related functions and modules docstrings
* Closes #372 
Generate the documentation locally. You will find the new documentation under `Tutorials` -> `Workflow configuration files`.
To review here on GitHub, the most relevant file is `docs/tutorials/user_config.rst`.
> Add user documentation on configuration files

- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
Closes #386. @amjjbonvin Now the calculation of the cluster-based caprieval scores is correct even if the cluster is underpopulated.
> amended clt_threshold behavior

- src/haddock/gear/expandable_parameters.py
- src/haddock/modules/__init__.py
- src/haddock/modules/base_cns_module.py
- tests/test_gear_expandable_parameters.py
---
Closes #449 
The `mol_` parameters is a class of the expandable parameters that gets populated at the `prepare_run` level by reading the number of molecules from the `molecules` parameter in the config file. However, when using the `--extend-run` option, this step is not produced. This PR adds the logic to expand the parameters accordingly.
> Populate `mol_` expandable parameters when using `--extend-run`

- src/haddock/gear/prepare_run.py
- tests/test_gear_prepare_run.py
---
Allows specifying single string when only one molecule is given as input. Hence, both cases are allowed:
```toml
molecules = ["mol1.pdb"]
```
or 
```toml
molecules = "mol1.pdb"
```
> Allows single entries in `molecules` parameter

- src/haddock/modules/analysis/seletopclusts/__init__.py
- [] Your PR is about writing documentation for already existing code :fire:
---
add cluster name to `seletopclusts.txt`
> add cluster name to `seletopclusts.txt`

- src/haddock/modules/analysis/clustfcc/__init__.py
---
Remove duplicated entry in `clustfcc.txt`
```
-----------------------------------------------
Cluster 7 (#4, n=6, top4_avg_score = -14.53 +-1.51)
clt_rank	model_name	score
1	rigidbody_6.pdb	-16.44
2	rigidbody_33.pdb	-15.37
3	rigidbody_28.pdb	-13.90
4	rigidbody_80.pdb	-12.42	*
5	rigidbody_80.pdb	-12.42	*
6	rigidbody_50.pdb	-10.54
```
```
-----------------------------------------------
Cluster 7 (#4, n=5, top4_avg_score = -14.53 +-1.51)
clt_rank	model_name	score
1	rigidbody_6.pdb	-16.44
2	rigidbody_33.pdb	-15.37
3	rigidbody_28.pdb	-13.90
4	rigidbody_80.pdb	-12.42	*
5	rigidbody_50.pdb	-10.54
```
> remove duplicated entry in `clustfcc.txt`

- src/haddock/gear/prepare_run.py
---
The `--restart` option was considering the restart number when copying files to the `data` dir, which forced the creation of too many folders that had no meaning in the workflow, for example:
```
drwxrwxr-x  2 joao joao 4096 Jun  6 11:44 00_topoaa/
drwxrwxr-x  2 joao joao 4096 Jun  6 11:44 01_caprieval/
drwxrwxr-x  2 joao joao 4096 Jun  6 11:44 02_caprieval/
drwxrwxr-x  2 joao joao 4096 Jun  6 11:44 03_flexref/
drwxrwxr-x  2 joao joao 4096 Jun  6 11:44 04_caprieval/
drwxrwxr-x  2 joao joao 4096 Jun  6 11:44 05_emref/
drwxrwxr-x  2 joao joao 4096 Jun  6 11:44 06_caprieval/
drwxrwxr-x  2 joao joao 4096 Jun  6 11:44 …
```
> Corrects bug in `--restart` option

- src/haddock/gear/prepare_run.py
---
Corrects the moment when the module's names are checked in the configuration file.
> Corrects check modules names in config on startup

- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
- CONTRIBUTING.md
- README.md
- tox.ini
Update CI workflows according to https://github.com/joaomcteixeira/python-project-skeleton/releases/tag/v0.9.2
The major change, `tox -e py39` is now `tox -e test`, thus making the `tox` testing not require specifying the python version.
Added also badges to the README file.
> Update CI workflows

- src/haddock/modules/topology/topoaa/__init__.py
---
The original implementation for reading `md5` hashes from `REMARK` lines was loose and caused errors in some structures with more complex `REMARK` lines. This PR corrects this behaviour by adding a robust checking and reading of md5 hashes and assigning them to `MODEL`s.
Previous tests pass.
`scoring` examples are currently broken because of this bug.
> Improve reading `md5` from `REMARK` lines

- src/haddock/libs/libpdb.py
- src/haddock/libs/libstructure.py
- src/haddock/modules/topology/topoaa/__init__.py
---
* Allow `topoaa` to be used in any part of the workflow
* when `topoaa` is not the first step, it will take the input from the previous module
* in the above case, (likely) the input molecule will contain the multiple chains (molecules) in the form of a complex. In these cases, `topoaa` does **not** split the molecules and, instead, creates the topology for the complex as a whole.
It's difficult to predict all possible scenarios from here onward. Do you know any other? Otherwise, we can merge and continue developing as the project progresses.
> Allows `topoaa` to run in different parts of the workflow

- src/haddock/gear/prepare_run.py
- src/haddock/modules/topology/topoaa/defaults.yaml
- tests/test_module_topoaa.py
---
Improves checking step parameters. Before, the mandatory parameters were getting accepted in the steps definitions, and that is not correct.
Adds the `molecules` parameter to `topoaa` as `hidden` bypass to facilitate the checking.
> Improves mandatory parameter check

- src/haddock/libs/libalign.py
- tests/test_libalign.py
---
Closes #472 by adding a call to an AlignError. It does not stop caprieval, but rather the `capri_ss.tsv` file is still produced for all those models that do not show an evident (empty chain) chain-matching error.
> added chain-matching AlignError

- docs/examples.md
- docs/tutorials/index.rst
There were two "Examples" titles in the docs. This corrects it.
> Improve two titles in documentation

- docs/modules/extras/exit.rst
- docs/modules/extras/index.rst
- docs/modules/index.rst
- examples/compare_runs.py
- examples/docking-protein-protein/docking-exit-test.cfg
- examples/docking-protein-protein/docking-extend-run-exit-test.cfg
- examples/docking-protein-protein/docking-restart-exit-test.cfg
- examples/run_tests.py
- src/haddock/core/exceptions.py
- src/haddock/gear/extend_run.py
- src/haddock/libs/libworkflow.py
- src/haddock/modules/__init__.py
- src/haddock/modules/extras/exit/__init__.py
- src/haddock/modules/extras/exit/defaults.yaml
---
* Added an `[exit]` module.
* Adding this module to the workflow will stop the workflow at that step
* I decided to make a module following the same hierarchy as for other modules. I found that cleaner than implementing an `if` process in a `gear` because doing so would require rewriting some tests.
* works with `--restart` and `--extend-run`
> Added `exit` module

- src/haddock/modules/topology/topoaa/__init__.py
---
* https://github.com/haddocking/haddock3/pull/261 introduced the `limit` parameter, for which `topoaa` started handling the models differently depending on the value of `limit`
* Recently, a lapse in https://github.com/haddocking/haddock3/pull/498 introduced a bug in which if `order=0` and `not limit`, the `mol_params_get` function is not defined.
* This PR solves this bug by correcting the `if-block` defining the `mol_params_get` function.
> Correct function selection in `topoaa` when `order=0` and `limit` is used (or not)

- examples/run_tests.py
* added `--restart 3` to integration tests in `run_tests.py`. This was missing from #494
> Add missing parameter in `run_tests.py` after #494

- docs/modules/sampling/rigidbody.rst
- src/haddock/modules/sampling/rigidbody/__init__.py
- tox.ini
---
I took the brief explanation of the `it0` step in the `local` tutorial for HADDOCK2.x and modified it slightly to fit as a short explanation for the `rigidbody` module.
Also, updated title in doc pages and added exceptions to doc linting in the pertinent files.
If you generate the docs `tox -e docs`, you'lll see this text renders in the HTML of the rigidbody page.
Feel welcome to edit further.
Cheers,
> Add documentation paragraph to `rigidbody` module description

- docs/modules/extras/exit.rst
- docs/modules/extras/index.rst
- src/haddock/modules/extras/__init__.py
- src/haddock/modules/extras/exit/__init__.py
* add the `__init__.py` file was missing in the extras from #494 
* add further documentation to the `exit` module
> add missing init file

- docs/modules/analysis/seletop.rst
Correct typo in module name in docs.
> Correct typo in documentation

- tox.ini
`isort` now only outputs errors.
> Removes `--verbosity` in `isort` lint check

- .github/workflows/pages.yml
Finally, found this to deploy the pages in a clean way: https://github.com/s0/git-publish-subdir-action#when-pushed-to-master-push-publicsite-to-the-gh-pages-branch-on-the-same-repo
Once @amjjbonvin updates the token, it should work. :crossed_fingers:
> Uses action to deploy pages

- CONTRIBUTING.md
- devtools/build_defaults_rst.py
- src/haddock/modules/_template_cat/README.md
- src/haddock/modules/_template_cat/_template_mod/__init__.py
- src/haddock/modules/_template_cat/_template_mod/defaults.yaml
- tox.ini
You are about to submit a new Pull Request. Before continuing, make sure you read the [contributing guidelines](CONTRIBUTING.md), and you comply with the following criteria:
---
* Add a template explaining how to develop a new module.
Please let me know if it is clear or if any information is missing according to your recent experience. Thanks
> Add template to write new modules

- src/haddock/gear/prepare_run.py
- tests/__init__.py
- tests/data/0_dummystep/file1.in
- tests/data/0_dummystep/folder/file2.in
- tests/test_gear_prepare_run.py
---
* Update the `--restart` option to cope with subfolders in steps.
* Thanks to @mgiulini for spotting this need for the new coming modules with subfolders.
> Update the `--restart` option to cope with subfolders in steps.

- src/haddock/modules/analysis/caprieval/capri.py
> Rank `capri_ss.tsv` by score and sort by `sortkey`

- src/haddock/libs/libontology.py
---
Closes #542. Tests and examples run as usual, but I don't know the reason why the method was developed like that in the first place, please tell me if I missed a point.
PS: a build test failed for no apparent reason. I don't think it's critical.
> changed retrieve_models logic

- src/haddock/libs/libontology.py
Reverts haddocking/haddock3#543
As discussed with @amjjbonvin and @rvhonorato it is better not to change this and stick to the original haddock2.4 logic, namely each input pdb must correspond to a single chain (except for scoring modules). In this way a complex can be refined by providing its chains separately.
#482 must take this into account when rebuilding the topologies of the models generated by openmm.
> Revert "changed retrieve_models logic"

- src/haddock/libs/libpdb.py
---
Closes #561 by reading the list of pdb files here https://github.com/haddocking/haddock3/blob/aa68fd3abf3ebe9e3c7c34812639761c7be9d69c/src/haddock/libs/libpdb.py#L256 always from the current directory, thus eliminating the path dependence and the potentially problematic usage of absolute paths.
> removed absolute paths in topoaa

- src/haddock/modules/analysis/caprieval/capri.py
---
Close #573 by changing the logic with which data is handled in `capri.rearrange_ss_output`. More specifically, when one of the expected capri files is not found in the folder, the workflow raises a warning.
https://github.com/haddocking/haddock3/blob/412e07dc8e41ab9ca6ee1cb09121344a55d054fe/src/haddock/modules/analysis/caprieval/capri.py#L654-L656
The files that have been correctly processed are then written to file.
NB: when the cluster analysis is performed, some models may have cluster information, but if the related capri job failed their capri quantities (fnat, dockq, ...) will be nan. Therefore, in case of …
> Fault tolerant caprieval

- src/haddock/clis/cli_clean.py
- src/haddock/clis/cli_unpack.py
- src/haddock/libs/libcli.py
- tests/test_libcli.py
---
Add the `--ncores` parameter to the `clean` and `unpack` clients.
> Add `--ncores` param to clean clients

- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
Closes #580 by implementing the sorting logic in capri_cluster_analysis. 
IMPORTANT: the rank in the caprieval table may differ from the rank coming from the `clustfcc` module, for instance when a different `clt_threshold` is defined. This is why I added a `caprieval_rank` field to the `capri_clt` table, which indicates the ranking according to the standard capri order (average of the score over the first `clt_threshold` models). Of course when a different sorting key (dockq, fnat, ...) is provided, the order changes and `caprieval_rank` remains unaltered (as in the single structure case).
Additionally, the …
> Fix clt order

- src/haddock/modules/refinement/emref/defaults.yaml
- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/refinement/mdref/defaults.yaml
- src/haddock/modules/sampling/rigidbody/defaults.yaml
- src/haddock/modules/topology/topoaa/defaults.yaml
---
Corrected some yaml files that in the description of parameters were still using booleans with capitals
> Changed in yaml files some boeleans to use lowercase for consistency

- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
---
Closes #589 by setting the attribute `restr_fname` to None when models to be refined have yet to be merged
> fixed handling of restr_fname in refinement modules

- docs/clients/cliclean.rst
- docs/clients/cliunpack.rst
- src/haddock/clis/cli.py
- src/haddock/clis/cli_clean.py
- src/haddock/clis/cli_cp.py
- src/haddock/clis/cli_unpack.py
- src/haddock/gear/clean_steps.py
- src/haddock/gear/extend_run.py
- src/haddock/gear/prepare_run.py
- src/haddock/libs/libio.py
- src/haddock/libs/libsubprocess.py
- src/haddock/libs/libworkflow.py
- tests/test_gear_clean_steps.py
- tests/test_libio.py
---
Closes #587
Closes #593
@amjjbonvin can you test this? In case you don't yet have my fork on your clone:
```
git remote add joaot https://github.com/joaomcteixeira/haddock3
git fetch joaot
git checkout unpackmore
```
And test some example.  Let me know if you with more to be done regarding **on the fly packing of output files**.
Cheers!
> Compress `.inp`, `.out`, and `.seed` in CNS Jobs on the fly

- src/haddock/libs/libparallel.py
- src/haddock/libs/libutil.py
- src/haddock/modules/__init__.py
- src/haddock/modules/defaults.yaml
- tests/test_libutil.py
---
The new `max_cpus` parameter is introduced.
> Implement option to use MAX CPUs and bypass the `N-1` rule for `local` mode.

- src/haddock/gear/prepare_run.py
- src/haddock/libs/libio.py
---
After preparing the run directory, and before starting the calculations, add writing permissions to all files in the `run_dir/data` directory.
@amjjbonvin can you test it to see wether it works on your side?
Closes #598
> add `w+` to data dir

- src/haddock/libs/libio.py
---
The last commit #599 broke the execution on OSX. This fix makes it work (tested both on OSX and Linux). The solution proposed by @mgiulini was to change `os.ST_WRITE` with `stat.S_IWUSR` in `src/haddock/libs/libio.py`
> Related to issue #598 - now compatible with OSX as well

- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
Closes #603 by
1. fixing the indexing error in the retrieval of receptor https://github.com/haddocking/haddock3/blob/f0ebd692277f5e58a34c22ce304d6b22c2824dfc/src/haddock/modules/analysis/caprieval/capri.py#L181-L182 and ligand https://github.com/haddocking/haddock3/blob/f0ebd692277f5e58a34c22ce304d6b22c2824dfc/src/haddock/modules/analysis/caprieval/capri.py#L202-L203 coordinates
2. correct the removal of the center of geometry of the receptor rather than that of the full complex https://github.com/haddocking/haddock3/blob/f0ebd692277f5e58a34c22ce304d6b22c2824dfc/src/haddock/modules/analysis/caprieval/capri.py#L177-L1 …
> Correct rmsds

- src/haddock/clis/cli_analyse.py
- src/haddock/libs/libplots.py
---
Closes #601 
Now the user can get static png scatter plots and box plots by adding the `--png` flag while running `haddock3-analyse`
Example:
`haddock3-analyse -r examples/docking-antibody-antigen/run1-ranairCDR-cltsel-test/ -m 5 --png=True
`
> added png option

- src/haddock/gear/extend_run.py
- src/haddock/gear/prepare_run.py
---
Closes #558 by adding a try except on UnicodeDecodeError. I still find the whole procedure of restarting quite complex and resource and time-consuming..
> solve unicode problem in restarting and copying runs

- src/haddock/modules/analysis/caprieval/capri.py
---
Closes #612 and prettifies the assignment of mean and std values of capri quantities.
> added score components to capri_clt

- src/haddock/modules/refinement/flexref/defaults.yaml
> Remove duplicated key in `src/haddock/modules/refinement/flexref/defaults.yaml`

- src/haddock/clis/cli.py
> removed other_params from call to postprocess

- examples/analysis/topoaa-rmsdmatrix-clustrmsd-test.cfg
- src/haddock/libs/libclust.py
- src/haddock/modules/analysis/clustrmsd/__init__.py
- src/haddock/modules/analysis/clustrmsd/clustrmsd.py
- src/haddock/modules/analysis/clustrmsd/defaults.yaml
- src/haddock/modules/analysis/rmsdmatrix/rmsd.py
- tests/test_module_clustrmsd.py
- tests/test_module_rmsdmatrix.py
---
Closes #555 by
- adding a function that finds rmsd clustering centers
- adding this cluster center info to the output `clustrmsd.txt` file
- modifying the default linkage criterion to `average`
- improves testing
- implements effectively the clustering threshold for the `distance` (cutoff) criterion, excluding clusters with population < 4 (default threshold). If no cluster is found such that this threshold is respected, the threshold is lowered by 1, as in `clustfcc`
> Adjust clustrmsd

- src/haddock/modules/analysis/seletopclusts/__init__.py
---
Closes #644 by changing the attributes of the models exported by `seletopclusts`, so that downstream modules refer to the files dumped by `seletopclusts` and not to files generated by previous modules. The file `seletopclusts.txt`, containing the exact mapping between models has not been touched.
> changed exported file names

- docs/INSTALL.md
Issue with the semantic for haddock3 definitions.
There are 4 haddock3 definitions in the same page:
1. HADDOCK3 the tool name
2. `haddock3` main branch directory
3. `haddock3` conda/venv python3 environnement
4. HADDOCK3 the command line tool
I feel it may be confusing some time and things are not allways called the same allong the documentation.
What about:
1. HADDOCK3: the tool name
2. **haddock3**: for main branch directory
3. `(haddock3)`: conda/venv python3 environnement
4. `>haddock3`: the command line tool
> Update INSTALL.md sementic on various haddock3

- src/haddock/modules/topology/topoaa/cns/bondglycans.cns
---
Corrected an atom naming typo that was causing wrong glycosidic linkages
> Fixes b16 glycan linkage issue #659

- src/haddock/modules/refinement/emref/cns/protein-ss-restraints-all.cns
- src/haddock/modules/refinement/emref/cns/protein-ss-restraints-alpha-beta.cns
- src/haddock/modules/refinement/emref/cns/protein-ss-restraints-alpha.cns
- src/haddock/modules/refinement/emref/cns/read_data.cns
- src/haddock/modules/refinement/flexref/cns/protein-ss-restraints-all.cns
- src/haddock/modules/refinement/flexref/cns/protein-ss-restraints-alpha-beta.cns
- src/haddock/modules/refinement/flexref/cns/protein-ss-restraints-alpha.cns
- src/haddock/modules/refinement/flexref/cns/read_data.cns
- src/haddock/modules/refinement/mdref/cns/protein-ss-restraints-all.cns
- src/haddock/modules/refinement/mdref/cns/protein-ss-restraints-alpha-beta.cns
- src/haddock/modules/refinement/mdref/cns/protein-ss-restraints-alpha.cns
- src/haddock/modules/refinement/mdref/cns/read_data.cns
- src/haddock/modules/scoring/mdscoring/cns/protein-ss-restraints-all.cns
- src/haddock/modules/scoring/mdscoring/cns/protein-ss-restraints-alpha-beta.cns
- src/haddock/modules/scoring/mdscoring/cns/protein-ss-restraints-alpha.cns
> Increased dihedral restraints array size - in line with haddock2.4/5

- src/haddock/libs/libplots.py
---
closes #665, please see [my comment ](https://github.com/haddocking/haddock3/issues/665#issuecomment-1591083352) that shows the hover text including `caprieval_rank`.
> Add `caprieval_rank` to hover text in scatter and box plots

- docs/INSTALL.md
- setup.py
---
In this PR, deprecation warning that are printed to user while running the command `python3 setup.py develop --no-deps` during the installation are silenced.
This is performed by the importation of the `warning` library and the two `EasyInstallDeprecationWarning` and `SetuptoolsDeprecationWarning` warning class from the `setuptools` library.
To compensate (and somehow remember) that these warnings exists, one line is added in the `docs/INSTALL.md` to justify the use of `python setup.py`.
(also related to #617)
> Hide install deprecation warnings

- setup.py
Solving issue with SetuptoolsDeprecationWarning exception class that has change location in the `setuptools` lib.
Should now be directly imported from `setuptools`.
> modify location of SetuptoolsDeprecationWarning

- src/haddock/gear/config.py
- src/haddock/gear/prepare_run.py
- src/haddock/gear/yaml2cfg.py
- src/haddock/modules/refinement/emref/defaults.yaml
- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/refinement/mdref/defaults.yaml
- src/haddock/modules/scoring/emscoring/defaults.yaml
- src/haddock/modules/scoring/mdscoring/defaults.yaml
- tests/test_gear_config.py
- tests/test_gear_prepare_run.py
- tests/test_modules_general.py
---
This PR aims at closing three issues:
- With the addition of a regular expression that checks the presence of upper case True and False in the .toml input file and lowering them on-the-fly, this closes #575 
- Also by checking values types and ranges/choices, by comparing values present in the defaults.yaml and parameter =  value present in the user provided .cfg file, this closes #487 
- Finally, a bunch of copies of the workflow haddock3 input files are now written in the `data` directory of the run. This includes the `original inputed file`, the `regular expression cleaned file` and the `enhanced full …
> Issuefixes

- src/haddock/libs/libplots.py
---
In this PR, I specify the versions of the react packages that are used to create the report file. This will avoid breaking the report.
> Pin versions of react libraries

- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/emref/defaults.yaml
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/refinement/mdref/defaults.yaml
---
Closes #689 by changing the max value of `sampling_factor` to 100 and adding a check at the python level such that if the product between the number of models and the `sampling_factor` is > 50 000 the code exits with an error.
I have absolutely no idea about why tests are failing..
> handled max sampling_factor

- src/haddock/libs/libplots.py
- tests/test_libplots.py
- ~~[ ] Your PR is about CNS~~
- ~~[ ] You wrote tests for the new code~~
- ~~[ ] Your PR is about writing documentation for already existing code :fire:~~
- ~~[ ] Your PR is about writing tests for already existing code :godmode:~~
---
As discussed before, we can move the codes of ngl viewer to the React component https://github.com/i-VRESSE/haddock3-analysis-components. In this pull request, changes are made to use the React component inside the HTML report code. Please run the haddock3-analyse command and inspect the report.html file. 
Related to https://github.com/i-VRESSE/haddock3-analysis-components/pull/5 …
> Use ngl component

- src/haddock/clis/cli_traceback.py
- tests/test_cli_traceback.py
---
Closes #700 : traceback is not run in postprocessing if the run has only analysis modules
> no traceback on pure analysis runs

- examples/analysis/topoaa-rmsdmatrix-clustrmsd-test.cfg
- examples/compare_runs.py
- examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
- examples/docking-protein-homotrimer/docking-protein-homotrimer-test.cfg
- examples/run_examples-full.py
- examples/run_tests.py
In this PR, issues running examples are solved.
Since PR #658 , parameters values are checked, and some issues with parameters arguments were discovered in the provided examples, making both `run_tests.py` and `run_examples-full.py` script failing.
Also, as the structure of the return value outputed by the `haddock.gear.config.load()` function has changed, the use of this function in both `run_tests.py` and `run_examples-full.py` had to be changed.
Hopefully, this closes #701 , and allow now to smoothly run the two examples scripts.
> Fixing issues running examples

- src/haddock/clis/cli_analyse.py
- src/haddock/libs/libplots.py
- src/haddock/libs/libworkflow.py
- tests/test_cli_analyse.py
- tests/test_libworkflow.py
---
Closes #713 by adding a check on the `clean` configuration parameter. If clean is True, then the structures will be gzipped in the last stage of the workflow, thus making them unaccessible in the html report. To solve this, at the postprocessing stage we check the clean parameter. If True, the file names are modified by adding the .gz suffix.
**Important** : this PR cannot take care of the case in which clean is False at the global level and True at the module level (and vice versa), as this would require a complicated traceback at the postprocessing stage, which is out of the scope of the analysis. This is a …
> show gzipped structures in analysis report

- tests/test_module_contmap.py
Solve the digit comparison issues while changing hardware by using `np.isclose()`
> modif float comparisons in contact map tests

- src/haddock/libs/libontology.py
Solve the `dictionary changed size during iteration` error in `topoaa` when 
Previous bug:
```
[2023-12-21 17:24:42,019 libutil ERROR] dictionary changed size during iteration
Traceback (most recent call last):
File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/libs/libutil.py", line 335, in log_error_and_exit
yield
File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/clis/cli.py", line 185, in main
workflow.run()
File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/libs/libworkflow.py", line 43, in run
step.execute()
File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/libs/libworkflow.py", line 155, in execute
self.module.run()  # type: ignore
File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/modules/base_cns_module.py", line 61, in run …
```
> update key deletion logic in topoaa

- src/haddock/cns/toppar/hemes-allhdg.top
- src/haddock/modules/topology/topoaa/cns/build-missing.cns
- src/haddock/modules/topology/topoaa/cns/generate-topology.cns
Updated missing atom generation script for issues related to parameter file changes.
Leads to stable energies, solving issue #785 
Now the generation/energies do no longer change when changing the param file
---
> Solves issue #785 about unstable energies when changing the param file

- examples/run_tests.py
- src/haddock/gear/prepare_run.py
- src/haddock/libs/libcns.py
- src/haddock/libs/libpdb.py
- src/haddock/modules/topology/topoaa/defaults.yaml
- tests/test_gear_prepare_run.py
---
Closes #741 by adding a check in libcns : for non-scoring modules, if the same chain ID is present in different PDBs then an error is raised and the execution is terminated.
The useless `prot_segid` parameter is also removed.
> Fix prot segid

- .github/workflows/github-to-gitlab-push-sync.yml
- action.yml
- entrypoint.sh
---
Following the instructions provided by Castiel to mirror our repo on the GitLab repo for EuroHPC.
Note that the build/action will fail (unless the target was set to this branch in `.github)/workflows/github-to-gitlab-push-sync.yml` ). It is now configured to mirror the main branch. 
Based on the instructions from the following repo: https://github.com/cniethammer/github-push-sync
> Adding mirror pushing to the Castiel EuroHPC GitLab repo

- src/haddock/clis/cli_analyse.py
- src/haddock/libs/libinteractive.py
- src/haddock/libs/libplots.py
- src/haddock/modules/analysis/caprieval/capri.py
- tests/data/capri_ss_-cluster.tsv
- tests/golden_data/capri_ss_example.tsv
- tests/test_module_caprieval.py
---
Closes #804 by using the underscore character in capri ss files.
> changed capri columns

- src/haddock/clis/cli_analyse.py
- src/haddock/libs/libplots.py
- tests/test_libplots.py
---
Closes #719
Uses Structures table from https://github.com/i-VRESSE/haddock3-analysis-components/pull/13 to render when there are no clusters.
> Side by side2

- src/haddock/libs/libplots.py
---
Follow up on #719 
The table report.html for other cluster was not rendered correctly.
With this PR it is rendered as
> Round other cluster + dont add score which was not there before

- devtools/build_defaults_rst.py
- docs/conf.py
- docs/examples.md
- docs/intro.md
- examples/analysis/topoaa-clustfcc-test.cfg
- examples/analysis/topoaa-ilrmsdmatrix-clustrmsd-test.cfg
- examples/compare_runs.py
- examples/docking-protein-glycan/docking-protein-glycan-ilrmsd-full.cfg
- examples/run_tests.py
- src/haddock/clis/cli_clean.py
- src/haddock/clis/cli_restraints.py
- src/haddock/clis/cli_unpack.py
- src/haddock/clis/restraints/restrain_bodies.py
- src/haddock/clis/restraints/validate_tbl.py
- src/haddock/gear/config.py
- src/haddock/gear/prepare_run.py
- src/haddock/modules/analysis/alascan/__init__.py
- src/haddock/modules/analysis/alascan/scan.py
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/clustfcc/__init__.py
- src/haddock/modules/analysis/clustrmsd/__init__.py
- src/haddock/modules/analysis/ilrmsdmatrix/__init__.py
- src/haddock/modules/analysis/seletop/__init__.py
- src/haddock/modules/analysis/seletopclusts/__init__.py
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/scoring/mdscoring/__init__.py
> Low level docs

- examples/compare_runs.py
- examples/run_tests.py
- src/haddock/clis/cli_traceback.py
- tests/test_cli_traceback.py
---
Closes #830 by ordering the traceback table according to the last column
> ordered traceback

- src/haddock/libs/libalign.py
Closes #843 by displacing the condition skipping residue names to be ignored in `libalign`
Thanks @mgiulini for discovering it !
> Fixing error in caprieval using shapes

- src/haddock/libs/libalign.py
- src/haddock/modules/analysis/caprieval/capri.py
Close #863 .
Adding an extra condition to solve `model2ref_chain_dict` mapping, when model chain is not present in the reference one.
> Chain match coords load issue

- src/haddock/modules/__init__.py
---
Closes #879 
Allows to save generated outputs even in the case when tolerance is under faulty threshold.
> Save outputs in case of faulty tolerance

- integration_tests/test_alascan.py
- src/haddock/libs/libplots.py
- src/haddock/modules/analysis/alascan/scan.py
- tests/golden_data/scan_protprot_complex_1.csv
- tests/test_module_alascan.py
---
Closes #866 by:
- changing the plot title
- changing the sign of the deltas
- removing the `ori_score` field, that was containing the difference between the emscoring score of the mutant and the existing score attribute of the wildtype (potentially coming from any module). This does not make much sense, as the only thing that matters is the difference between the two emscoring values
> Improve alascan output

- src/haddock/libs/libcns.py
- src/haddock/libs/libontology.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/flexref/cns/flexref.cns
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/refinement/mdref/cns/mdref.cns
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/sampling/rigidbody/cns/bestener.cns
- src/haddock/modules/sampling/rigidbody/cns/rigidbody.cns
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/scoring/mdscoring/__init__.py
- src/haddock/modules/scoring/mdscoring/cns/mdscoring.cns
- tests/test_libcns.py
- tests/test_libontology.py
---
This PR adds a `seed` property to `libontology.PDBFile` and refactors `libcns` to use this seed when creating the `.inp` files/strings. I also added several tests that were missing for both `libontology` and `libcns`.
I have also changed the `.cns` files that would create this `.seed` files.
In summary what happens is; in `rigidbody` the seed is set according to:
```python
seed = self.params["iniseed"] * idx
```
This is passed to `libcns.prepare_cns_input` which will create a "eval line" with this value.
This seed number is also added to the _expected output_, and subsequent modules will either read this seed - …
> Avoid generating `.seed` files

- integration_tests/test_caprieval.py
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
This PR updates the `caprieval` module to benefit from the `less_io` parameter. Now when setting this `less_io` parameter, no "intermediary" files will be generated.
To achieve this I had to refactor `CAPRI.run` to return a copy of itself so that an instance with the updated values (`self.fnat`, `self.irmsd`, etc) can be retrieved as a simple `results` property of the `Scheduler` execution engine. 
There is a `rearrange_ss_capri_output` which is responsible for joining the intermediate files - however this function was also ranking according to the score. So I removed this logic of ranking into another …
> Use `less_io` parameter in `caprieval`

- src/haddock/modules/scoring/mdscoring/defaults.yaml
---
The haddock-runner detected duplicated parameters in the `default.yaml` file of the `mdscoring` module. This pull request removes the duplication of the w_air parameter.
> removed duplicated w_air parameter

- src/haddock/clis/cli_mpi.py
- tests/test_cli_mpi.py
---
This PR adds lazy-loading of the `mpi4py` module, avoiding issues during testing
> lazy load MPI module and COMM variable

- integration_tests/test_caprieval.py
- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
This PR refactors `capri.extract_data_from_capri_class` to mimic the behaviour of the `make_output` method that retrieves the `PDBFile.unw_energies` property that will later be used when writing the output.
> Refactor `capri.extract_data_from_capri_class` to propagate the model's energy terms

- integration_tests/test_mpi.py
- integration_tests/test_rigidbody.py
- src/haddock/modules/sampling/rigidbody/__init__.py
---
This PR changes the rigidbody module to use `prepare_cns_input_sequential` if the execution mode is different than `local` - it also adds more tests
> Use `prepare_cns_input_sequential` when `mode` is not local

- integration_tests/test_caprieval.py
---
This PR updates the integration tests for `caprieval` module that were ignored in #957 and streamlines the checking process adding some helper functions to handle the polymorphic nature of the `capri_ss`  and `capri_clt`  files
> update `caprieval` integration tests

- src/haddock/gear/clean_steps.py
---
Close #936 
In batch mode, more files are created (e.g: `.job` and `.err`).
They were not part of the file extensions to be removed during the cleaning process.
This is now fixed !
> Clean intermediate files in batch mode

- src/haddock/libs/libparallel.py
---
This PR changes the log level when reporting exceptions in the task execution. `exception` will log it with ERROR level - which is wrong since the execution can move forward. This PR changes it so its logged as WARNING
> change log level of exceptions in the Worker's run method

- src/haddock/gear/prepare_run.py
- src/haddock/gear/yaml2cfg.py
- src/haddock/modules/__init__.py
- src/haddock/modules/defaults.yaml
- tests/test_gear_prepare_run.py
---
This PR adds a logic to check for parameter incompatibilities. 
For example; with #918 I added a new parameter called `less_io` however you cannot use this parameter together with `mode=batch`.
So now you can define a new `incompatible` property of a given parameter in the `haddock.modules.defaults.yaml`;
```yaml
less_io:
incompatible:
mode: batch
```
Which will then be validated when the run is being setup.
> Add logic to check for incompatible parameters

- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
This PR adds the extraction and combination of cluster-related information from the models into the `extract_data_from_capri_class` method. I've also updated the test to cover this behaviour and added a deprecation notice to the soon-to-be-removed branch with `less_io=false` - see #970 
Also keep in mind that this retrieval of clustering information should not be done via the model object - by doing this we are breaking the modular design by using the PDBFile object as means to transport information instead of the ontology object. Should be addressed in a separate PR tho
> Propagate cluster related properties in `caprieval`

- integration_tests/test_caprieval.py
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/capri.py
- src/haddock/modules/analysis/caprieval/defaults.yaml
- tests/test_module_caprieval.py
---
Closes #989 by adding a new parameter `global_rmsd` in `[caprieval]`, where the full structure RMSD is now computed, regardless of any reference/ligands chains.
Still a sequence alignment is performed.
Additionally, few modifications were made on the uni/integration tests for code optimization and readability.
> Single chain caprieval

- integration_tests/golden_data/ambig.tbl
- integration_tests/golden_data/hbond.tbl
- integration_tests/golden_data/unambig.tbl
- integration_tests/test_restraints.py
- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/emref/cns/read_data.cns
- src/haddock/modules/refinement/emref/cns/read_noes.cns
- src/haddock/modules/refinement/flexref/cns/read_data.cns
- src/haddock/modules/refinement/flexref/cns/read_noes.cns
- src/haddock/modules/refinement/mdref/cns/mdref.cns
- src/haddock/modules/refinement/mdref/cns/read_data.cns
- src/haddock/modules/refinement/mdref/cns/read_noes.cns
- src/haddock/modules/sampling/rigidbody/cns/read_noes.cns
- src/haddock/modules/sampling/rigidbody/cns/rigidbody.cns
---
hbond restraints provide a separate class of restraints that can be used as various stages with their own force constants.  In the current code these were read under the `dist` class if unambiguous restraints were read and otherwise in the `ambig` class, meaning they would be subjected to random removal.
This pull request corrects this behaviour by changing the relevant CNS scripts to make sure hbond restraints are read under a separate `hbon` class.
As hbonds restraints can be used for any type of distance restraints in principle, their contribution is now also added to the distance restraint energy of …
> make sure `hbond` restraints are read under a separate class

- src/haddock/modules/refinement/flexref/cns/flexref.cns
Solves issue #1000.
In the `flexref` module, the tad factor defining the time step for an MD integrations step is now automatically reduced from the default of 8 to 4 for the high temperature initial stage of the simulated annealing protocol. This will reduce possible job failures (models crashing) in the flexref module.
Integration test will be added once the `integration-tests` branch is merged.
> Automatically reduce the tadfactor to 4 when fully flexible segments are defined

- examples/peptide-cyclisation/cyclise-peptide-full.cfg
- examples/peptide-cyclisation/cyclise-peptide-test.cfg
- integration_tests/test_caprieval.py
- integration_tests/test_emref.py
- integration_tests/test_flexref.py
- integration_tests/test_mdref.py
- integration_tests/test_restraints.py
- integration_tests/test_rigidbody.py
- integration_tests/test_topoaa.py
- src/haddock/libs/libcns.py
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/capri.py
- src/haddock/modules/defaults.yaml
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/scoring/mdscoring/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
- tests/test_libcns.py
Modify parameter name `less_io` to `debug`, and inverse conditions using this parameter.
Closes #1033
> less_io to debug

- src/haddock/clis/cli.py
- tests/test_cli.py
Modify main CLI `recipe` parameter name to `workflow` for better understanding.
#1039
> Update main cli description

- .github/workflows/ci.yml
- tests/conftest.py
- tests/test_cli_restraints.py
- tests/test_gear_haddockmodel.py
- tests/test_module_alascan.py
- tests/test_module_caprieval.py
- tests/test_module_clustfcc.py
- tests/test_module_clustrmsd.py
- tests/test_module_contmap.py
- tests/test_module_emscoring.py
- tests/test_module_flexref.py
- tests/test_module_ilrmsdmatrix.py
- tests/test_module_mdscoring.py
- tests/test_module_rigidbody.py
- tests/test_module_rmsdmatrix.py
- tests/test_module_seletopclusts.py
- tests/test_module_topoaa.py
- tests/test_modules_general.py
This PR goes into #1042 and refactors the tests to account for the behaviour of `tempfile` changed in 3.12
> Refactor `tempfile` usage in tests

- pyproject.toml
- src/haddock/libs/libinteractive.py
- upgrades numpy to 2*
- solves a tie-breaking issue: when the score is equal the pandas sorting in `libinteractive` was giving inconsistent results (depending on the architecture). Adding an additional, unambiguous field (the `caprieval_rank`) to the sorting solves the issue.
Closes #1092
> numpy upgrade

- src/haddock/modules/topology/topocg/aa2cg.py
- src/haddock/modules/topology/topocg/helper.py
Here, I adapt the code to produce DSSP usable pdb files and remove the usage of the DSSP function from the BioPython library, instead using the command line version.
Not related to an issue
The warning "No SS definition found for residue: ..." was removed, since if DSSP is installed and works, a secondary structure will be applied. 
I will look into the Codacy reports issues with the aa2cg.py script for a following pull request.
> Correction of the usage of DSSP in the topocg module

- integration_tests/golden_data/workflow.cfg
- integration_tests/test_full_workflow.py
- src/haddock/clis/cli_analyse.py
Closes #1122 by changing the absolute path to the step folder to be analysed with the relative path. This allows the analysis to be executed on every "cleaned" run (before it was only working for standard, not cleaned runs)
Additionally, a quite comprehensive integration test is being added, in which a short but full workflow is executed including cleaning and analysis. Then two interactive commands are executed (`haddock3-re clustfcc` and `haddock3-re score`) and checked. Last, the two newly created interactive folders are analysed and the code checks for the existence of the expected report.
> fixed analysis on cleaned, downloaded runs

- src/haddock/libs/libcns.py
- src/haddock/libs/libpdb.py
- src/haddock/modules/sampling/rigidbody/__init__.py
- tests/test_libpdb.py
adds a check for duplicated chains for any possible combination of molecules at the rigidbody level even when the job preparation is done in parallel. If an error is detected, the workflow stops without executing any computation.
Closes #1177
> refactored check for chain combinations

- src/haddock/libs/libutil.py
Try to solve the problem related to core detection on MacOS.
The implemented solution is to go back to the original function `os.cpu_count()`.
While this may not be fully accurate, it allows to at least return the number of cores available on MacOS machines.
On Linux systems, the `os.sched_getaffinity(0)` function is used, returning the number of cores allocated to the process, which is a better solution for HPC and SLURM executions.
Closes #1182
> back to basics for macos users when detecting number of cores

- integration_tests/test_mdscoring.py
Allow for `0.01` digit fluctuation when comparing haddock score and per-interface score in `integration-tests/test_mdscoring.py`.
Closes #1184
> allow for digit fluctuation in mdscoring integration tests

- src/haddock/clis/cli_restraints.py
- src/haddock/clis/restraints/passive_from_active.py
adds the radius argument and removes deprecation message from haddock3-restraints. When it will superseded, better to remove it completely, but having a deprecation message is detrimental, as the output of the CLI has to be redirected to output files.
Closes #1205 and closes #1203
> Add radius passive from active

- .github/workflows/ci.yml
Update the CI to be run on an interval - this should help us react faster to issues such as #1251 or other breaking changes upstream
> add schedule to `ci.yml`

- src/haddock/gear/greetings.py
Extremely minor change: linked https://bioexcel.eu/bioexcel-survey-2025/ instead of 2024 one in greetings.py
> Added link to BioExcel 2025 survey

- src/haddock/clis/restraints/active_passive_to_ambig.py
- tests/test_cli_restraints.py
added value error message when no active residues are present. A test was also added to ensure the correct execution of this check.
Closes #1244
> Active passive to ambig exception

- src/haddock/modules/analysis/seletopclusts/seletopclusts.py
Closes #1264 by removing the verbose model mapping log call.
> removed verbose log call from seletopclusts

- src/haddock/modules/topology/topoaa/__init__.py
PR #1273  added a bug when importing ensembles.
This PR solves this issue by creating a copy of the parameters for the molecules during `topoaa`, therefore allowing to use the `.pop` method without touching the initial parameters.
Closes #1296
> make deepcopy of molecule params so they can be used multiple times

- CHANGELOG.md
- src/haddock/clis/cli_restraints.py
- src/haddock/clis/restraints/restrain_ligand.py
- tests/test_cli_restraints.py
As proposed by an external user, this PR introduce an additional subcommand `restrain-ligand` into the `haddock3-restraints` CLI.
This new sub-command allows to select a residue name from a PDB file and generate unambiguous restraints keeping it in place.
This is an adaptation of the script used in the [shape restraint](https://www.bonvinlab.org/education/HADDOCK24/shape-small-molecule/) docking set of script (`restrain_ligand.py`), and also similar to what can be performed by the `restrain` command from the [haddock-restraints](https://github.com/haddocking/haddock-restraints) package.
```
Usage:
haddock3-restraints restrain_ligand <pdb_file> <ligand_name> -r <radius> -d <deviation> -n <max_nb_restraints>
positional arguments:
pdb_file              Input PDB file.
ligand_name …
```
> Restrain ligand

- CHANGELOG.md
- integration_tests/test_alascan.py
- src/haddock/libs/libplots.py
- src/haddock/modules/analysis/alascan/scan.py
- tests/test_libplots.py
- tests/test_module_alascan.py
This PR adds standard deviation computation when performing cluster analysis in the `alascan` module.
Closes #1332
> computing std dev in alascan

- .gitignore
- CHANGELOG.md
- pyproject.toml
- setup.py
- src/haddock/clis/wrapper_haddock_restraints.py
- tests/test_wrapper_haddock_restraints.py
This PR changes `setup.py` to allow for a more generic download of binaries and it adds a new download during installation for `haddock-restraints`.
I also added `src/haddock/clis/wrapper_haddock_restraints.py` which is just a wrapper to make `haddock-restraitns` available in the `PATH`.
#1353
I have updated the user guide with an entry about this: https://www.bonvinlab.org/haddock3-user-manual/clis.html
> distribute `haddock-restraints` binary

- .github/workflows/ci.yml
- pyproject.toml
- src/haddock/libs/libnotebooks.py
- tests/__init__.py
- tests/test_libnotebooks.py
This PR is a cherry-pick from #1360 which added the `libnotebooks`.
This lib contains helper functions that should be used in jupyternotebooks 
https://github.com/haddocking/haddock3/issues/1367
> add `libnotebooks`

- .github/workflows/stale.yml
This PR adds `stale.yml` which contains an action to check for stale pull-requests and issues. It will mark them as stale after 30 days of inactivity and if no reaction is made to this warning, the bot then closes it after 5 days. 
Once an issue/pr is marked as stale, the bot will give a warning and to re-start the timer someone must react to this warning by commenting on it or removing the label. Then the timer starts again, and after more 30 days of inactivity it's triggered again so on and so forth.
This is relevant to give an indication to external users which issues/pr as being worked on or are planned (postponed by commenting on it) and will also automatically clean-up the repository.
Currently there are issues/pull-requests that are years old, some others many months old, and it's …
> add action to identify stale issues/PRs
