- README.md
Following a conversation with @rvhonorato - thx!
> Clarifies main branch status

- .gitignore
- src/haddock/libs/libutil.py
- src/haddock/pdbutil.py
Abstracts a repeated code checking for pdb file variations.
This is a minor change helping improving modularity while I study the current code.
> Reduces code repetition in pdbutil when checking for new files

- README.md
corrects typo in `ln` command!
> corrects ln typo

- src/haddock/clis/cli.py
- src/haddock/gear/greetings.py
Moves greetings messages to its specific module under the `gear/` package and does very minor changes in the greetings module itself.
> Moves and adjusts greeting messages

- src/haddock/gear/greetings.py
- src/haddock/libs/libworkflow.py
Corrects critical var names after #105 and #106, sorry for this lapse.
> Corrects var names critical errors

- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
What a shame...
Closes #132
Could you check also the new `start` added in the topology module?
> Correct enumerate syntax

- src/haddock/gear/prepare_run.py
Close #149 
Give it a try, working on my machine. :+1:
> Solves missing repeated modules during `prepare_run`

- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/flexref/cns/flexref.cns
- src/haddock/modules/refinement/mdref/cns/mdref.cns
If not simply use the defined seed
> Added check to make sure the seed file is present before reading.

- src/haddock/modules/analysis/caprieval/__init__.py
Minor change :) 
***
Closes #157
> Add scores to `caprieval` output

- requirements.txt
- requirements.yml
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/defaults.cfg
This reverts commit 9c564b20345a795599df5136c55a75bd2ea5ce11, reversing
changes made to 1bd79f029503a77917af4ba7d1d46aa6973fb66d.
> Revert "Merge pull request #182 from haddocking/153"

- src/haddock/libs/libhpc.py
Ops made a small error when calculating the % of completed jobs.
> Fix HPC completed percentage

- src/haddock/libs/libparallel.py
> Fix sorting of paralel jobs

- INSTALL.md
Updates and clarifies install instructions.
> Updates clarifies install instructions

- src/haddock/gear/greetings.py
- src/haddock/gear/prepare_run.py
I know it is very boring to be deleting folders when we are running tests, but it is just too dangerous to have haddock3 deleting folders without asking.
> Do not delete the run dir.

- src/haddock/libs/libparallel.py
> Fix `libparallel` to correctly use `ncores`

- src/haddock/modules/__init__.py
> remove prints / asserts

- examples/run_examples.py
> corrects dictionary to tuple of tuples in `run_examples.py`

- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/emref/defaults.cfg
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/flexref/defaults.cfg
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/refinement/mdref/defaults.cfg
- src/haddock/modules/sampling/rigidbody/__init__.py
- src/haddock/modules/sampling/rigidbody/defaults.cfg
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/scoring/emscoring/defaults.cfg
- src/haddock/modules/topology/topoaa/__init__.py
- src/haddock/modules/topology/topoaa/defaults.cfg
I could swear the correct spelling was `tolerancy`, turns out its `tolerance` 😅
> `tolerancy` should be `tolerance`

- src/haddock/libs/libontology.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/scoring/emscoring/__init__.py
This PR closes #294 
~I did not run any sort of tests, not sure how to run them since it changed in #291.~
Result of the test below
> Update modules to pass the correct variable to `ModuleIO`

- src/haddock/core/cns_paths.py
- tests/test_cns_paths.py
> Add unittests to `cns_paths` lib

- src/haddock/core/mandatory.yaml
- src/haddock/gear/parameters.py
- tests/test_mandatory_params.py
Closes #304 
Add a `yaml` with the description of mandatory parameters.
@sverhoeven can you comment to see if it's okay?
> Add YAML for mandatory parameters

- src/haddock/__init__.py
- src/haddock/gear/yaml2cfg.py
- tests/test_yaml2cfg.py
Closes #321
@sverhoeven you might need to update this also
> ignores `explvl = hidden`

- examples/docking-protein-DNA/docking-protein-DNA-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-test.cfg
- examples/docking-protein-peptide/docking-protein-peptide-full.cfg
- src/haddock/modules/defaults.yaml
- src/haddock/modules/refinement/emref/cns/contactairs.cns
- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/emref/cns/print_coorheader.cns
- src/haddock/modules/refinement/emref/cns/read_data.cns
- src/haddock/modules/refinement/emref/cns/read_noes.cns
- src/haddock/modules/refinement/emref/cns/setflags.cns
- src/haddock/modules/refinement/emref/defaults.yaml
- src/haddock/modules/sampling/rigidbody/defaults.yaml
- Added all content to the emref yaml file
- Adapted some CNS scripts to use new parameter names
- Added documentation to the general yaml file
- Added new parameter to the general yaml file to specify the batch system (storm or torque)
Tests completing fine.
Tox reports no errors :-)
> Emref yaml documentation and script cleaning

- CONTRIBUTING.md
Adds also some sentences for the future.
> Reviews and updates `CONTRIBUTING`

- examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
- examples/refine-complex/refine-complex-test.cfg
- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/emref/defaults.yaml
- src/haddock/modules/refinement/mdref/cns/cm-restraints.cns
- src/haddock/modules/refinement/mdref/cns/contactairs.cns
- src/haddock/modules/refinement/mdref/cns/mdref.cns
- src/haddock/modules/refinement/mdref/cns/print_coorheader.cns
- src/haddock/modules/refinement/mdref/cns/read_data.cns
- src/haddock/modules/refinement/mdref/cns/read_noes.cns
- src/haddock/modules/refinement/mdref/cns/setflags.cns
- src/haddock/modules/refinement/mdref/cns/symmultimer.cns
- src/haddock/modules/refinement/mdref/defaults.yaml
And few edits to other modules (small corrections).
All tests passing. Note that some changes might be observed in the mdref output since I changed the default behaviour for random removal of restraints to true (the proper default - before was set to false).
> Mdref yaml documentation and CNS scripts updates

- src/haddock/clis/cli.py
- src/haddock/libs/libutil.py
- src/haddock/libs/libworkflow.py
- tests/test_libutil.py
Closes #317
Each module now reports the time it took to run. The whole run reports the time it took to run.
> Add elapsed time to modules and to the whole run

- examples/docking-protein-DNA/docking-protein-DNA-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
- examples/docking-protein-DNA/docking-protein-DNA-test.cfg
- examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
- examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
- examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/flexref/cns/flexref.cns
- src/haddock/modules/refinement/flexref/cns/print_coorheader.cns
- src/haddock/modules/refinement/flexref/cns/read_data.cns
- src/haddock/modules/refinement/flexref/cns/read_noes.cns
- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/refinement/mdref/cns/mdref.cns
- src/haddock/modules/refinement/mdref/defaults.yaml
Added the documentation to the flexref yaml file and adapted where needed / cleaned the CNS scripts.
> Flexref yaml documentation

- src/haddock/modules/analysis/clustfcc/__init__.py
You are about to submit a new Pull Request. Before continuing make sure
you read the [contributing guidelines](CONTRIBUTING.md) and you comply
with the following criteria:
as explained in contributing guidelines. You wrote explanatory comments for
those tricky parts.
`python run_tests.py -b`
other programming languages to HADDOCK3
small functions instead. But, you can use classes if there's a purpose.
by the HADDOCK team
* * *
* 
Fix #345 by adding the cluster centers to `ModuleIO` considering the cluster centers
> Consider cluster centers in `clustfcc`

- README.md
Adds a section for users to sign the google forms supporting HADDOCK3. Since the form is on the group's page, I thought it could be useful having it here as well. What do you think?
> Googleform

- examples/run_tests.py
- tox.ini
corrects for missing `import os`.
> added missing os

- tests/test_modules_general.py
The answer is "No" :godmode:
Thanks @mgiulini 
https://github.com/haddocking/haddock3/pull/418#pullrequestreview-960017330
> Correct minor typo

- requirements.txt
- requirements.yml
Update `pdb-tools version` to `2.4.5`.
> update `pdb-tools version` to `2.4.5`

- tests/test_module_clustfcc.py
---
Added some basic tests for module `clustfcc`. These tests make sure all the expected output files are correctly created for a simple example.
> Test module clustfcc

- src/haddock/modules/refinement/flexref/defaults.yaml
---
Switched a number of parameters in the default.yaml file to hidden for the flexref module
> Changed some parameters to hidden

- README.md
- tox.ini
Update the README file for the beta release. Please give your contributions.
> Update README file for Beta version

- src/haddock/modules/analysis/clustfcc/__init__.py
- src/haddock/modules/analysis/seletopclusts/__init__.py
---
Improves the clustering to make it more useful, closes #453 and closes #438
> Enhance clustering protocols

- src/haddock/modules/topology/topoaa/__init__.py
- tests/golden_data/ens_header.pdb
- tests/test_module_topoaa.py
- [] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
---
Adds tests for `topoaa` and fix a bug introduced in #459
> add tests to `topoaa`

- .gitignore
As noted by @rvhonorato , thanks :+1:
> add haddock3-docs to .gitignore

- src/haddock/modules/analysis/seletopclusts/__init__.py
- [] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
---
Closes #470
> Add missing header to `seletopclusts.txt`

- examples/docking-protein-ligand/docking-protein-ligand-test.cfg
- src/haddock/modules/analysis/clustrmsd/defaults.yaml
- tests/test_module_clustrmsd.py
> added single linkage as clustrmsd default

- docs/examples.md
- examples/compare_runs.py
- examples/docking-antibody-antigen/data/ambig-CDR-NMR-CSP.tbl
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-NMR-CSP-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-NMR-CSP-test.cfg
- examples/run_tests.py
---
Added new example for the antibody-antigen using epitope residues identified from NMR CSP experiments as described in our online tutorial at https://www.bonvinlab.org/education/HADDOCK24/HADDOCK24-antibody-antigen/#bonus---using-nmr-titration-data-to-guide-the-docking
> Added new antibody-antigen example using epitope definition from NMR

- requirements.txt
- requirements.yml
Manually update the `pdb-tools` version in the requirement files.
> Update `pdb-tools` version.

- src/haddock/modules/topology/topoaa/defaults.yaml
---
* Add documentation to the `limit` parameter in `topoaa`
* Related to https://github.com/haddocking/haddock3/pull/261
> Add documentation to the `limit` parameter in `topoaa`

- src/haddock/core/supported_molecules.py
---
* In #144, I forgot to add `shape.top` to the list of supported residues.
* This PR is also an example of how to add new molecules
> Added `shape.top` to the supported residues

- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
Closes #506 by creating a small function, check_chains, that checks if the expected chains are part of the observed chains. In case they are not, it sticks to the observed chains.
> implemented check_chains

- .github/workflows/pages.yml
@amjjbonvin I think this action should do the trick. we can actually accept this PR first than the Karma one to see if it works.
> Add action to deploy pages

- .github/workflows/pages.yml
The typical with GA, they never work at first go.
> changed to py39 in GA for pages

- CONTRIBUTING.md
- README.md
- src/haddock/gear/clean_steps.py
- src/haddock/gear/expandable_parameters.py
- src/haddock/libs/libstructure.py
- src/haddock/modules/refinement/emref/defaults.yaml
- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/refinement/mdref/defaults.yaml
---
* Updates how to contribute to documentation.
* Correct issues in docs.
Let me know if it is clean.
> Update guidelines to contribute to documentation

- README.md
Update the `docs` badge to match the `pages.yml` file.
> Update the `docs` badge to match the `pages.yml` file.

- src/haddock/modules/refinement/emref/defaults.yaml
> removed sampling parameter

- src/haddock/clis/cli_cp.py
- tests/clis/hd3_copy/run1/3_seletop/io.json
- tests/clis/hd3_copy/run2_ref/2_seletop/io.json
- tests/test_cli_copy.py
---
Closes #559 by checking which steps are effectively present in the `data` folder.
> addressed bug in haddock3-copy cli

- src/haddock/libs/libclust.py
- src/haddock/modules/analysis/clustfcc/__init__.py
- src/haddock/modules/analysis/clustrmsd/__init__.py
- tests/test_libclust.py
> Unclustered structures

- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
> fixed dockq calculation

- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-NMR-CSP-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-NMR-CSP-test.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-clt-full-mpi.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-clt-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-clt-test.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-full-mpi.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-test.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-clt-full-mpi.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-clt-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-clt-test.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-full-mpi.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-cltsel-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
- examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
- examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
- examples/docking-protein-ligand/docking-protein-ligand-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-cltsel-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
- examples/docking-protein-protein/docking-protein-protein-cltsel-full.cfg
- examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
- examples/docking-protein-protein/docking-protein-protein-full.cfg
- examples/docking-protein-protein/docking-protein-protein-mdref-full.cfg
- examples/scoring/capri-scoring-test.cfg
- src/haddock/modules/analysis/seletopclusts/__init__.py
- src/haddock/modules/analysis/seletopclusts/defaults.yaml
---
Closes #566
All examples have been changed accordingly. It's now much easier to select a certain number of clusters. Default value has been set to 1000 (meaning typically all clusters will be selected).
> Top cluster integer

- src/haddock/libs/libclust.py
- src/haddock/modules/analysis/clustfcc/__init__.py
- src/haddock/modules/analysis/clustrmsd/__init__.py
- tests/test_libclust.py
- tests/test_module_clustfcc.py
- tests/test_module_clustrmsd.py
---
Closes #581 . code is prettified a bit as well
> removed cluster file from tests and prettified code

- src/haddock/gear/yaml2cfg.py
- tests/configs/yaml2cfg_converted.cfg
- tests/configs/yaml2cfg_converted_no_header.cfg
- tests/test_gear_yaml2cfg.py
---
Prints boolean variables in lower characters.
> Updates `haddock3-cfg` for `toml` compatibility  - bool variables

- src/haddock/modules/defaults.yaml
---
*detele this line and explain your PR here*
> Changed max_cpus to true as default (and its description)

- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/refinement/mdref/defaults.yaml
- src/haddock/modules/scoring/mdscoring/defaults.yaml
> increased tolerance for MD modules

- src/haddock/__init__.py
- src/haddock/core/defaults.py
---
This should fix #519 by simply adding the stream handler in the base `__init__.py`
> change log handler

- src/haddock/modules/analysis/caprieval/capri.py
> correct model-cluster-ranking

- src/haddock/cns/toppar/carbohydrate.param
- src/haddock/cns/toppar/carbohydrate.top
- src/haddock/modules/refinement/mdref/defaults.yaml
- src/haddock/modules/topology/topoaa/cns/bondglycans.cns
https://github.com/haddocking/haddock/issues/559
https://github.com/haddocking/haddock/issues/550
---
> Add support for new carbohydrate linkages in line with 2.4

- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/flexref/cns/flexref.cns
- src/haddock/modules/refinement/mdref/cns/mdref.cns
- src/haddock/modules/scoring/emscoring/cns/calc_free-ene.cns
- src/haddock/modules/scoring/emscoring/cns/emscoring.cns
- src/haddock/modules/scoring/mdscoring/cns/mdscoring.cns
> bugfix for when nemsteps=0

- src/haddock/modules/scoring/__init__.py
- tests/test_module_emscoring.py
- tests/test_module_mdscoring.py
---
Closes #529 by using pandas to output the scoring data in `emscoring.tsv` and `mdscoring.tsv`
> score-sorted scoring files

- src/haddock/modules/refinement/emref/cns/print_coorheader.cns
- src/haddock/modules/refinement/flexref/cns/print_coorheader.cns
- src/haddock/modules/refinement/mdref/cns/print_coorheader.cns
- src/haddock/modules/sampling/rigidbody/cns/print_coorheader.cns
- src/haddock/modules/scoring/emscoring/cns/print_coorheader.cns
- src/haddock/modules/scoring/mdscoring/cns/print_coorheader.cns
---
Add the CNS machinery to write multiple input PDBs to the header of the PDB files
> fixes issue #662

- src/haddock/gear/haddockmodel.py
- tests/test_gear_haddockmodel.py
---
Closes #721 and adds some necessary tests for the haddockmodel gear
> added symmetry energy to output

- src/haddock/libs/libplots.py
> added bsa box plot

- examples/analysis/contmap-test.cfg
- src/haddock/modules/analysis/contactmap/contmap.py
---
Updated the colour scheme of the chord chart to have a better distinction between the type of amino acids and the contacts they made. 
An update of issue #733
> Updated color scheme of chord chart

- requirements.txt
> updated freesasa

- examples/docking-protein-peptide/docking-protein-peptide-cltsel-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-mdref-test.cfg
- examples/docking-protein-peptide/docking-protein-peptide-test.cfg
---
Solves issue #767
Increased the number of refinement steps in the flexref module to match the defaults of the 2.4 server
Corrected one config file that had by mistake a rmsdmatrix step added.
> updated protein-peptide example and test config file - issue #767

- src/haddock/libs/libplots.py
---
Closes #770 by calculating and showing mean and std deviation for the four best scoring models of each cluster, for each scatter plot in the final report.
> corrected crossbar values

- src/haddock/libs/libplots.py
---
On request of @amjjbonvin show 11 clusters = 10 top ranked + other cluster
> Show top 10 ranked clusters + Other cluster

- examples/thirdparty/gdock/gdock-integration.cfg
- tests/test_examples_general.py
---
Closes #817 by adding a test that validates all the exposed cfg files
> Validate example workflows

- src/haddock/libs/libalign.py
- src/haddock/modules/analysis/ilrmsdmatrix/ilrmsd.py
- tests/test_libalign.py
---
Fixes #826 by allowing to filter complexes based on a subset of chains present in the file.
> Work arround chain matching in IL-RMSDMatrix

- src/haddock/clis/cli_traceback.py
- src/haddock/libs/libplots.py
- tests/test_cli_traceback.py
---
Closes #840 by adding a consensus plot and saving the reduced traceback dataframe
> added traceback plot and sum of ranks file

- src/haddock/libs/libplots.py
! URGENT !
Quick fix of huge error when creating plots !
Basically broke all the generated plots in one line of code.
> Fix offlinemode

- src/haddock/modules/analysis/contactmap/contmap.py
---
Closes #848 by adding dashed lines separating chains in the heatmaps generated by the `contactmap` module.
> Upgrade contact heatmap

- examples/compare_runs.py
- examples/run_tests.py
- src/haddock/core/defaults.py
- src/haddock/modules/analysis/caprieval/__init__.py
- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
> Fix auto analysis

- src/haddock/modules/analysis/contactmap/defaults.yaml
- src/haddock/modules/extras/exit/defaults.yaml
- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/sampling/gdock/defaults.yaml
- src/haddock/modules/sampling/lightdock/defaults.yaml
- src/haddock/modules/topology/topoaa/defaults.yaml
> added groups data

- examples/compare_runs.py
- examples/run_tests.py
> Added alascan modules to tests execution and comparison

- src/haddock/modules/topology/topoaa/__init__.py
Close #877 by searching for model origin in input ensembles and adding it as a prefix.
> Add prefix to model names from input ensemble

- src/haddock/modules/__init__.py
> Remove faulty outputs before saving io.json

- integration_tests/test_ilrmsdmatrix.py
- src/haddock/modules/analysis/ilrmsdmatrix/__init__.py
- src/haddock/modules/analysis/ilrmsdmatrix/defaults.yaml
- src/haddock/modules/analysis/ilrmsdmatrix/ilrmsd.py
- src/haddock/modules/analysis/rmsdmatrix/rmsd.py
- tests/test_module_ilrmsdmatrix.py
---
Closes #827 by adding a new parameter `contact_distance_cutoff` enabling to tune the definition of contacts in module `ilrmsdmatrix`.
> Define contact distance cutoff parameter in ilrmsdmatrix

- src/haddock/modules/analysis/seletopclusts/seletopclusts.py
> corrected absolute path in seletopclusts

- src/haddock/modules/topology/topoaa/__init__.py
> check that file exists before renaming

- examples/scoring/capri-scoring-test.cfg
- examples/scoring/emscoring-mdscoring-test.cfg
- examples/scoring/emscoring-test.cfg
- examples/scoring/mdscoring-test.cfg
- src/haddock/modules/scoring/__init__.py
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/scoring/emscoring/cns/print_coorheader.cns
- src/haddock/modules/scoring/emscoring/defaults.yaml
- src/haddock/modules/scoring/mdscoring/__init__.py
- src/haddock/modules/scoring/mdscoring/cns/print_coorheader.cns
- src/haddock/modules/scoring/mdscoring/defaults.yaml
---
Added the option to the scoring modules to output per interface scores in the header of the PDB files
> Per interface scoring

- src/haddock/clis/cli_traceback.py
- src/haddock/libs/libplots.py
> remove deprecation warnings

- src/haddock/gear/greetings.py
This PR updates the `international_good_byes` list 🤓
> add more good byes

- src/haddock/modules/refinement/mdref/defaults.yaml
> increased max sampling_factor

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
This PR updates the repository templates for 
- `bug_report.md`
- `feature_request.md`
- `pull_request_template.md`
And I have added a new `question.md` template
I've updated the topics so that we can extract better information from the issues. I've also changed it to use comments to make it more friendly and provide longer explanations.
> Update repository templates

- src/haddock/modules/analysis/clustrmsd/defaults.yaml
> changed min and max clust_cutoff

- src/haddock/modules/analysis/contactmap/__init__.py
- src/haddock/modules/analysis/seletop/__init__.py
- src/haddock/modules/refinement/emref/__init__.py
- src/haddock/modules/refinement/flexref/__init__.py
- src/haddock/modules/refinement/mdref/__init__.py
- src/haddock/modules/topology/topoaa/__init__.py
- src/haddock/modules/topology/topocg/__init__.py
> better description for some modules

- src/haddock/modules/analysis/caprieval/capri.py
- tests/test_module_caprieval.py
---
Closes #956 by adding ilrmsd columns to capri_clt files
> added ilrmsd to capri clt

- src/haddock/libs/libinteractive.py
- tests/test_libinteractive.py
---
Closes #971 by fixing the interactive re-scoring and adding a test for unclustered data rescoring
> Fix rescore

- src/haddock/clis/cli.py
- src/haddock/gear/greetings.py
Closes #996 by adding links to feedback/issues at the end of a workflow.
> links to feedbacks

- examples/compare_runs.py
- examples/docking-protein-DNA/docking-protein-DNA-cmrest-test.cfg
- examples/run_tests.py
- src/haddock/modules/refinement/flexref/cns/cm-restraints.cns
- src/haddock/modules/refinement/flexref/cns/flexref.cns
- src/haddock/modules/sampling/rigidbody/cns/cm-restraints.cns
- src/haddock/modules/sampling/rigidbody/cns/rigidbody.cns
Also added a protein-DNA cm-restrained docking test.
Checked all CNS output files for errors, none detected
---
> remove dead code related to DNA in `cm_restraints.cns` 

- src/haddock/modules/refinement/emref/defaults.yaml
- src/haddock/modules/refinement/flexref/defaults.yaml
- src/haddock/modules/refinement/mdref/defaults.yaml
- src/haddock/modules/scoring/emscoring/defaults.yaml
- src/haddock/modules/scoring/mdscoring/defaults.yaml
- src/haddock/modules/topology/topoaa/defaults.yaml
Lower expertise level of ligands params to `easy`
Closes #914 
Required for smooth integration of ligand scenario in the web-app
> lower expertise level of ligands params

- DISCLAIMER.md
Add a disclaimer to the repo for the commercial use of the CNS-related modules of HADDOCK3
> Added DISCLAIMER statement

- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-clt-full-mpi.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-clt-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-clt-test.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-full-mpi.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-test.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-clt-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-full-mpi.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-full.cfg
- examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
- examples/docking-protein-homotrimer/docking-protein-homotrimer-test.cfg
Modify `ranair` parameter in some antibody antigen examples to the correct value
Closes #1044
> Fixing some examples workflow configuration files

- examples/docking-protein-DNA/docking-protein-DNA-cltsel-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-cmrest-test.cfg
- examples/docking-protein-DNA/docking-protein-DNA-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
- examples/docking-protein-DNA/docking-protein-DNA-test.cfg
Setting the `w_desolv = 0` for all DNA examples.
> Updating DNA examples to match parameters in tutorial

- examples/peptide-cyclisation/cyclise-peptide-3wne-full.cfg
- examples/peptide-cyclisation/cyclise-peptide-full.cfg
Add an additional example for cyclic peptides
#1056
> update cyclic peptides examples

- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-NMR-CSP-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-clt-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-clt-full.cfg
- examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-full.cfg
- examples/docking-multiple-ambig/docking-multiple-tbls-clt-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-cltsel-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-full.cfg
- examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
- examples/docking-protein-glycan/docking-flexref-protein-glycan-full.cfg
- examples/docking-protein-glycan/docking-protein-glycan-full.cfg
- examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
- examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
- examples/docking-protein-ligand/docking-protein-ligand-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-cltsel-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-full.cfg
- examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
- examples/docking-protein-protein/docking-protein-protein-cltsel-full.cfg
- examples/docking-protein-protein/docking-protein-protein-full.cfg
- examples/docking-protein-protein/docking-protein-protein-hpc-test.cfg
- examples/docking-protein-protein/docking-protein-protein-mdref-full.cfg
- src/haddock/modules/defaults.yaml
The incompatibility of the debug mode with batch mode was wrong set.
The correct combination is: for batch mode debug must be set to true (i.e. we write all files)
Correct now in `src/haddock/modules/defaults.cfg`
> Corrected incompatibility values for the debug parameter

- examples/docking-protein-protein-CG/docking-protein-protein-CG-test.cfg
- integration_tests/test_emref-cg.py
- src/haddock/modules/refinement/emref/cns/charge-beads-interactions.cns
- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/emref/cns/read_param.cns
- src/haddock/modules/refinement/emref/defaults.yaml
Added support for coarse graining in emref modules (similar implementation as for flexref).
Added integration test
> Adding CG support to emref module

- tests/test_module_caprieval.py
Closes #1128 by removing 0 from the pool of possible values that can be assigned to clt_id, clt_rank, clt_model_rank in `tests/test_module_caprieval.py::test_extract_data_from_capri_class `
> fix random error

- integration_tests/test_full_workflow.py
- src/haddock/clis/cli_analyse.py
Closes #1121 by modifying the initialization of the capri object within postprocessing
it also adds a new integration test that checks for existing analysis. This is the first workflow-wide integration test and may be extended to account for more cases.
> Analysis not capri

- src/haddock/modules/scoring/__init__.py
- src/haddock/modules/scoring/emscoring/__init__.py
- src/haddock/modules/scoring/mdscoring/__init__.py
reverses the current order in which models are exported and the per interface scoring is done. If the tolerance is not met, the standard exception is reported
Closes #1105
> caught CNS exception in scoring modules

- src/haddock/modules/topology/topocg/aa2cg.py
> Minor fix of aa2cg script

- src/haddock/gear/greetings.py
Adding the link to bioexcel forum at the end of the run, printed in the log.
This is performed by updated the greening url dict:
- adding the link to the bioexcel forum
- removing (commenting) the bioexcel user survey
Closes #1160
> adding bioexcel forum

- DEVELOPMENT.md
- docs/INSTALL.md
Adding instructions on how to replace the CNS version coming with pip install in case of problems.
https://github.com/haddocking/haddock3/issues/1191
> Added CNS troubleshooting instructions (issue #1191)

- src/haddock/libs/libalign.py
- src/haddock/modules/analysis/caprieval/capri.py
removes debug log calls
Closes #1198
> removed debug log calls

- CONTRIBUTING.md
Small modification on the path where to find the README on how to create a new module.
#1255
> fix path in CONTRIBUTING.md

- README.md
> added biorxiv ref

- pyproject.toml
> changed version

- README.md
Updating the README with url to the user maual
Closes #1277
> Update README with url to user manual

- integration_tests/test_alascan.py
- src/haddock/cns/toppar/protein-allhdg5-4-noCter.link
- src/haddock/cns/toppar/protein-allhdg5-4-noNter.link
- src/haddock/cns/toppar/protein-allhdg5-4-noter.link
- src/haddock/cns/toppar/protein-allhdg5-4.link
- src/haddock/cns/toppar/protein-allhdg5-4.param
- src/haddock/cns/toppar/protein-allhdg5-4.top
- src/haddock/modules/analysis/alascan/__init__.py
- src/haddock/modules/analysis/alascan/defaults.yaml
- src/haddock/modules/analysis/alascan/scan.py
This PR adds the topology and parameters definition for the citruline (CIR) residue
Closes #1272
> adding citruline parameters/topology definition

- src/haddock/clis/restraints/restrain_ligand.py
Fix bug that appeared while running ci workflows.
> Fix restrain lig test

- pyproject.toml
Bumping haddock3 version to create a tagged version, PyPI release and docker container
> haddock3 v.2025.08.0 stable release

- CHANGELOG.md
- src/haddock/modules/refinement/emref/cns/check_coordinates.cns
- src/haddock/modules/refinement/emref/cns/emref.cns
- src/haddock/modules/refinement/flexref/cns/check_coordinates.cns
- src/haddock/modules/refinement/flexref/cns/flexref.cns
- src/haddock/modules/refinement/mdref/cns/check_coordinates.cns
- src/haddock/modules/refinement/mdref/cns/mdref.cns
- src/haddock/modules/sampling/rigidbody/cns/check_coordinates.cns
- src/haddock/modules/sampling/rigidbody/cns/rigidbody.cns
- src/haddock/modules/scoring/emscoring/cns/check_coordinates.cns
- src/haddock/modules/scoring/emscoring/cns/emscoring.cns
- src/haddock/modules/scoring/mdscoring/cns/check_coordinates.cns
- src/haddock/modules/scoring/mdscoring/cns/mdscoring.cns
- src/haddock/modules/topology/topoaa/cns/check_coordinates.cns
- src/haddock/modules/topology/topoaa/cns/generate-topology.cns
Added check for max/min possible coordinate for writing PDB files to the various CNS modules (topoaa, rigidbody, emref, flexref, mdref, emscoring, mdscoring)
Closes #1350
> Addresses issue #1350 - coordinates check

- src/haddock/libs/libaa2cg.py
- src/haddock/modules/refinement/cgtoaa/cns/read_param.cns
In this branch, we correct the files used for the "ligands", renamed as "cofactors". Furthermore, when a cofactor is encountered in topocg, it will now be ignored. However, cgtoaa will regenerate it.
> Cg haddock topocg fix

- pyproject.toml
DOES NOT APPLY
Update minimum `mpi4py`  to `4.0.2`
> update minimum `mpi4py` version

- notebooks/HADDOCK3-antibody-antigen.ipynb
Removed spurious section header
Removed duplication in alascan analysis
None
> Cleaned the antibody-antigen notebook
